### ISSUE TITLE
Дюп проводов

### ISSUE THREAD

**Issue by Yorodoshi** [TerraFirmaGreg-Team/Modpack-Modern#130]
### Вы используете последнюю доступную версию?

Yes

### Среда запуска

Сервер|Одиночная 

### Новые миры

Да

### Ожидаемое поведение

Нормальные раскрафты в упаковщике

### Фактическое поведение

Рецепты любых проводов после 2х в итоге дают 3\5 листа резины и 4х\16х провод (в зависимости от материала) по итогу.
Что даёт дюп резины на 2х\4х\8х кабелях и потерю на 16х

### Действия по воспроизведению

https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/128903188/37e1d9e3-519d-4e80-b445-9fb35fb612ef

### Дополнительная информация

Not TFG bug

Потому-что в греге кривые декрафты проводов

**Comment by FriendlyCube** [comment]
сейчас данного бага нет
