### ISSUE TITLE
No recipe for brass plated blocks

### ISSUE THREAD

**Issue by Wyrmlet** [TerraFirmaGreg-Team/Modpack-Modern#184]
### Version modpack Used

0.5.1

### Environment

Singleplayer

### New Worlds

Yes

### Expected Behavior

Brass plated blocks are craftable and useable for glassblowing.

### Actual Behavior

Brass plated blocks have no recipe.

### Steps to Reproduce

Attempt to use any glassblowing recipe from TFC that involves basin pouring or table pouring.

**Comment by SpeeeDCraft** [comment]
Simple brass blocks from gtceu can be used there, but I intended to make tfc blocks available in the future.

**Comment by SpeeeDCraft** [comment]
After some thought, it was decided to leave the plated tfc blocks disabled. GTCEU brass blocks and kaolinite clay blocks are now used in place of them as before. This will be described in the quests in the future.
