### ISSUE TITLE
Дюп инструментов

### ISSUE THREAD

**Issue by AngryUnp** [TerraFirmaGreg-Team/Modpack-Modern#185]
### Версия модпака.

0.5.1

### Среда запуска

Одиночка

### Новые миры

Да

### Ожидаемое поведение

Два предмета превратятся в один более целый

### Фактическое поведение

У двух теряется прочность(вместо исчезновения) и создаётся новый более целый (а с зажатым шифтом и вовсе оптом)

### Действия по воспроизведению

![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/136995410/3c678659-ec15-4966-b19f-244e8c8422f5)
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/136995410/ae4b554b-e9c6-4ae8-9f0b-a380554292f9)

### Дополнительная информация

В 0.4.3 этого не было

**Comment by SpeeeDCraft** [comment]
Ого, это баг грега, о котором в дсе мы говорил сто раз, но все равно находятся те, кто репортят
