### ISSUE TITLE
НЕ загружается мир после обновления с 0.6.10

### ISSUE THREAD

**Issue by maximtart** [TerraFirmaGreg-Team/Modpack-Modern#222]
### Версия модпака.

0.6.11

### Среда запуска

одиночная игра

### Новые миры

Нет

### Ожидаемое поведение

мир загрузится как ожидается

### Фактическое поведение

Отображается ошибка:
**Errors in surrently selected data packs prevented the world from loading. You can either try to load it with only the vanila data pack ("safe mode")  or go to the tile screen and fix it manualy**

### Действия по воспроизведению

1. обновил с 0.6.10
2. запустил игру
3. загружаю мир

### Дополнительная информация

никаких дополнительных ресурс паков, дата паков, текстур или шейдеров не устанавливал
использую только то что в комплекте с модом.
Загрузка в safe mode  не помогает
как поправить?

**Comment by maximtart** [comment]
Вернулся на 0.6.10 -- мир загрузился нормально

**Comment by SpeeeDCraft** [comment]
Попробуй с нуля скачать, только что это сделал и все работает

**Comment by maximtart** [comment]
я немного нуб в "этих ваших модпаках", как мне мир сохранить? а то 200+ дней неохота переигрывать((
