### ISSUE TITLE
Доменка и грек трубы корраптят сейф

### ISSUE THREAD

**Issue by FallenMind** [TerraFirmaGreg-Team/Modpack-Modern#233]
### Версия модпака.

0.6.11

### Среда запуска

Одиночная игра, и я уверен что и в мультиплеере

### С какой стороны краш

Сервер

### Новые миры

Да

### Действия по воспроизведению

Доменная печь выливает содержимое в блок под собой после выполнения работы. В контейнеры грека всё хорошо, но как только в трубу - мгновенный краш и коррапт сейфа

### Отчет о сбое

[crash-2024-02-10_19.52.28-server.txt](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/files/14228783/crash-2024-02-10_19.52.28-server.txt)

### Дополнительная информация

не удаляйте это, почините(( это так удобно

**Comment by FriendlyCube** [comment]
Совместимость тфк и Грега ¯⁠\⁠_⁠(⁠ツ⁠)⁠_⁠/⁠¯
Пока ты можешь просто поставить drum из Грега тыкнуть по нему отвёрткой и ниже поставить трубы

**Comment by Exzept1on** [comment]
После обновлений грега, трубы перестали принимать жидкость в таком кейсе, из чего следует, что повторить краш более невозможно (слив в контейнеры все так же работает)
