### ISSUE TITLE
Печки перестали работать(или это фича?)

### ISSUE THREAD

**Issue by maximtart** [TerraFirmaGreg-Team/Modpack-Modern#240]
### Version modpack Used

0.6.13

### Environment

Одиночная

### New Worlds

Yes

### Expected Behavior

Пожарить любой тип породы - пробовал гематит, уголь, сфалерит - вех видов
в большой паровой и базовой электрической печках
Так же пробовал раскрошенный вариант
получить, например, слиток цинка 

### Actual Behavior

крафт не запускается

### Steps to Reproduce

закинуть породу в печь

### Additional Information

откатился на 0.6.11 -- все работает 
или это фича? тогда зачем печь?

**Comment by KraftKraftKraft** [comment]
Это косяк грегтеха. Ждем фикса. МОжешь попробовать откатиться до предыдущей версии раз в сингле играешь
