### ISSUE TITLE
Не работает крафт Small Pile Of Flint Dust через инвентарь/верстак

### ISSUE THREAD

**Issue by Maxitanker** [TerraFirmaGreg-Team/Modpack-Modern#241]
### Версия модпака.

0.6.13

### Среда запуска

Сервер

### Новые миры

Не уверен

### Ожидаемое поведение

Получить Small Pile of Flint Dust из Flint Dust при крафте через инвентарь/верстак/Mechanical Crafter

Крафт в EMI
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/47298638/f3326996-92ae-4127-8550-679e7f438363)

### Фактическое поведение

Крафт не работает, нет возможности получить нужную пыль через инвентарь/верстак/Mechanical Crafter

### Действия по воспроизведению

1. Получить Flint Dust
2. Попытаться скрафтить из него Small Pile of Flint Dust в инвентаре
3. Убедиться, что крафт не работает

### Дополнительная информация

В целом замечено, что остальная пыль также не может перекрафтиться в обычных верстаках в свои малые аналоги.
Для геймплея Small Pile of Flint Dust важен, так как он используется для приготовления стекла в GT. На таком раннем этапе развития использовать еще одну машину только чтобы разделить кучку пыли - слишком дорого

![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/47298638/6ba4749e-a45b-4f10-a430-802b8691b85e)

**Comment by SpeeeDCraft** [comment]
![Uploading image.png…]()

**Comment by Maxitanker** [comment]
Шайтан, оно серьезно не работало. Проверил, всё норм, сорян.
