### ISSUE TITLE
Kaolinite Clay does not spawn

### ISSUE THREAD

**Issue by Halohup** [TerraFirmaGreg-Team/Modpack-Modern#242]
### Version modpack Used

0.6.12-4

### Environment

Singleplayer

### New Worlds

Yes

### Expected Behavior

Kaolinite spawns in sedimentary blocks in kaolinite biomes

### Actual Behavior

Kaolinite blocks do not spawn. Verified using worldedit to detect entire biomes to replace Kaolinite blocks with Stone and Worldedit did not register any blocks. 

### Steps to Reproduce

Create new world with default settings

**Comment by Wyrmlet** [comment]
So _that's_ why I couldn't find any! I do remember searching for kaolin clay for ages, ended up just cheating it in through creative.

**Comment by BabBimmaBome** [comment]
I find lots in plateau tropical savanna biomes

**Comment by papdawin** [comment]
It does spawn, it's just extremely rare. I had to travel 14.000 blocks south just to find a vein.

**Comment by SpeeeDCraft** [comment]
bad way to find clay.. dead
