### ISSUE TITLE
Food rots in jei menu

### ISSUE THREAD

**Issue by Nexuee** [TerraFirmaGreg-Team/Modpack-Modern#249]
### Version modpack Used

0.6.15

### Environment

Official server

### New Worlds

Unsure

### Expected Behavior

foods should be normal and not rotten

### Actual Behavior

After playing long enough on a world the foods in jei will rot basically making it so you cant check their nutritional values.

### Steps to Reproduce

play for about 9+ days and jei foods will rot in menu

**Comment by Exzept1on** [comment]
Fixed in dev
