### ISSUE TITLE
[Bug] Papyrus related task showed unfinished dispite wild papyrus was found

### ISSUE THREAD

**Issue by chemlzh** [TerraFirmaGreg-Team/Modpack-Modern#261]
### Version modpack Used

0.6.15

### Environment

Singleplayer

### New Worlds

Yes

### Expected Behavior

When we found a wild papyrus crop, wild papyrus task should be finished, thus unlocking next tasks for cutting and soaking papyrus pieces.

### Actual Behavior

Papyrus and its seeds were obtained, and papers, resistors and some other machines are made. However, papyrus tasks showed unfinished, thus downstream tasks cannot be finished.

![2024-02-23_14 29 55](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/32123043/eed4939d-ccf0-43cc-b7d4-4f282d94038f)

![2024-02-23_14 29 50](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/32123043/2d7b24a7-6f36-44b5-9df7-74c96e3324fd)

### Steps to Reproduce

1. we found a wild papyrus crop.
2. we harvested it by left clicking for some time.
3. Papyrus and its seeds were got, and tasks should be finished.

**Comment by BabBimmaBome** [comment]
Plant it

**Comment by chemlzh** [comment]
I see, though I feel a little strange, since breaking wild papyrus crops will still obtain papyrus, thus finishing papermaking. I think unlocking condition that papyrus should plant and harvest at least once seems to be too harsh, because if you are fortunate, you can find 5-6 wild papyrus crops once, which is enough to make resistors and circuits.
