### ISSUE TITLE
Chains Smithing Final 3 is Backwards

### ISSUE THREAD

**Issue by BrandicCustos** [TerraFirmaGreg-Team/Modpack-Modern#264]
### Version modpack Used

TerraFirmaGreg-1.20.x-0.6.15

### Environment

Singleplayer & Multiplayer

### New Worlds

Yes

### Expected Behavior

You take an ingot in the anvil and select chain. You complete the minigame finishing with Draw Hammer Hammer and get 16 chains.

### Actual Behavior

The order is reversed from what the GUI shows. You have to Hammer Hammer Draw in order to complete the smithing minigame. 

Multiple recipes seem to be wrong:
![Copper Chain Wrong Recipe](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/120141598/58adb58d-456f-47ec-b3cb-99aaf2a14eb5)
![Steel Chain Wrong Recipe](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/120141598/7ce3dcca-1bd9-431a-a96f-047979d74385)

Order contrary to GUI shows are correct:
![order backwards](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/120141598/a30aca78-b784-4cec-aede-23517af1e564)

### Steps to Reproduce

Try to make chains in an anvil and play the smithing minigame. Try to do it like any other item. No matter now perfect you are, you will not succeed. Now do the last 3 in reverse and it works.

### Additional Information

I tested it with copper and steel, but it could well be all of them.

**Comment by SpeeeDCraft** [comment]
TFC has the same recipe for chains, idk bug this or not

**Comment by Exzept1on** [comment]
![image](https://github.com/user-attachments/assets/a2bce535-2385-4793-8b10-ccd50e05b82b)

All works fine, I can forge chains. Not a bug.
