### ISSUE TITLE
Автоматический полив в теплице

### ISSUE THREAD

**Issue by InvisibleSpectator** [TerraFirmaGreg-Team/Modpack-Modern#269]
### Ваш вопрос

Осталась ли возможность автоматического полива в теплицах из firmalife? Я вижу, что отключены крафты насосов из террафирмы, но крафт медных труб, спринклеров и ирригационных баков оставлен. Можно ли как-то их использовать? Разные комбинации греговских труб и его же помпы к результату не привели. Что я делаю не так?

Версия 0.6.15

**Comment by SpeeeDCraft** [comment]
Все делаешь правильно, просто поливка в данный момент не доступна для firmalife, из-за некоторых косяков TFC и частично сборки, поправим в будущем обновлении

**Comment by Exzept1on** [comment]
Fixed in dev
