### ISSUE TITLE
Ванильные железные слитки в примитивной эре

### ISSUE THREAD

**Issue by FlekGeKei** [TerraFirmaGreg-Team/Modpack-Modern#304]
### Версия модпака.

0.7.2

### Среда запуска

сервер (скачанный из официального сайта Forge)

### Новые миры

Нет

### Ожидаемое поведение

Что железная пыль не будет преплавляться в Crucible.

### Фактическое поведение

Оно прерплавилось в ванильные слитки.

### Действия по воспроизведению

1) Раскочегарить Charcoal Forge до максимальной теплоты при помощи Bellows.
2) Кинуть железную пыль в Crucible (другие способы не проверял).
3) Получить бесполезные ванильные железные слитки в примитивной эре.

**Comment by FlekGeKei** [comment]
я это понимаю, но почему я имею возможность получить какое-то бесполезное дерьмо

**Comment by FriendlyCube** [comment]
иметь возможность сделать дерьмо тоже круто
