### ISSUE TITLE
[Bug?] TNT-related recipes should use nitration mixture, and implosion compressor should consume both gem dusts and TNT

### ISSUE THREAD

**Issue by chemlzh** [TerraFirmaGreg-Team/Modpack-Modern#313]
### Version modpack Used

0.7.2

### Environment

Singleplayer

### New Worlds

No

### Expected Behavior

1) TNT has nitric function group, and it's produced by mixing methylbenzene (toluene) with condensed nitric acid and sulfic acid mixture in real life (that is also called nitration mixture).
2) In quest interface, the preposition quest of ender pearl includes TNT crafting, therefore the original crafting recipes seem to be putting TNT and ender pearl dusts into implosion compressor.

### Actual Behavior

1) TNT is made just from toluene and sulfic acid.
2) Ender pearl can be crafted with only ender pearl dusts in implosion compressor.

### Steps to Reproduce

1) Put nitration mixture and gelled toluene in the chemical reactor, and it does not work.
2) Put ender pearl dusts and TNT in the implosion compressor, and only ender pearl dusts are consumed.

**Comment by SpeeeDCraft** [comment]
gtceu moment?

**Comment by chemlzh** [comment]
> gtceu moment?

I have discussed with other MC players, and we reached the conclusion that gelled toluene recipe is a GTM feature, since gelled toluene is also crafting with toluene and sulfic acid in original GTM. However, implosion compressor seems like a bug, because GT5 & GTCEu do consume TNT.

**Comment by Exzept1on** [comment]
I'll assume this has been fixed.
