### ISSUE TITLE
Can't craft the Long Distance Fluid/Item Pipeline

### ISSUE THREAD

**Issue by JMmumu** [TerraFirmaGreg-Team/Modpack-Modern#314]
### Version modpack Used

0.7.2

### Environment

whatever

### New Worlds

Yes

### Expected Behavior

Craft successful this thing

### Actual Behavior

The assembler do nothing
![2FF5AA586460D9379A9B1290C84A81FC](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/42163799/fb0a6a63-9ee6-4850-baed-f7c7e2d49a3a)

### Steps to Reproduce

![87F8DB4D24C10376756B96D033B63E92](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/42163799/e31ef8a3-933f-40d0-bb28-424212e7e455)
![C177318F667E28DC603652158B3664C4](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/42163799/2eae31e8-4f13-427d-880b-c314aabf9b1e)
make this item

### Additional Information

The recipe is to make 64 at a time, because TFC changed the maximum number(32) of stacks causing the craft to be unsuccessful, maybe a change to the properties will fix it?

**Comment by V-asakot** [comment]
They barely work anyway

**Comment by SpeeeDCraft** [comment]
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/52341158/7a0d033f-f2e0-45d8-adff-e7be9df603b2)
maybe need a circuit?

**Comment by JMmumu** [comment]
> ![image](https://private-user-images.githubusercontent.com/52341158/319982629-7a0d033f-f2e0-45d8-adff-e7be9df603b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzNzk3MTUsIm5iZiI6MTcxMjM3OTQxNSwicGF0aCI6Ii81MjM0MTE1OC8zMTk5ODI2MjktN2EwZDAzM2YtZjJlMC00NWQ4LWFkZmYtZTdiZTlkZjYwM2IyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDA0NTY1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlMGVkNmVhNTE2NTA2NmNiMjVhZmUyYmFiYzU3ZDM1Y2ExZTdiMzk0ODdjMzk0Nzg3N2Y5NTc5YWY3NjliYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zbeuLDuejJlVMNb4RDjlgMg1OHWRcWvEVyBAwONTpOE) maybe need a circuit?

The machine has “ghost circuit”, a special solt

**Comment by SpeeeDCraft** [comment]
I know, I was just checking, okaaay then

**Comment by Exzept1on** [comment]
Now I tried to change the recipe for them, it still doesn't work on kraft, I assume that the GTM error.

**Comment by WaterMelwin** [comment]
:(

**Comment by ndrwksr** [comment]
Is the issue that they only stack to 32, the recipe makes 64, and the assembler only has one output slot?

**Comment by Exzept1on** [comment]
> Is the issue that they only stack to 32, the recipe makes 64, and the assembler only has one output slot?

true

**Comment by Exzept1on** [comment]
Fixed in 0.7.13-14
