### ISSUE TITLE
The greenhouse system is unable to irrigate automatically.

### ISSUE THREAD

**Issue by kangyx000** [TerraFirmaGreg-Team/Modpack-Modern#323]
### Version modpack Used

0.7.2

### Environment

server

### New Worlds

Yes

### Expected Behavior

In version 0.7.2, it is not possible to craft a greenhouse water pump for irrigation. Currently, there is no way to water the crops in the greenhouse.

### Actual Behavior

The greenhouse cannot be used properly.

### Steps to Reproduce

Unable to craft the water pump.

**Comment by Exzept1on** [comment]
We know this. Fixed in update after 0.7.3 (on 0.7.4)

**Comment by VantablackWolf** [comment]
How exactly did you fix it? I have tried nearly everything, and cannot figure it out.

**Comment by AryaElendril** [comment]
Our community server has a few players experiencing this same struggle. Is there an update as to how the sprinkler has been made to function? The pump is still unavailable.

**Comment by Exzept1on** [comment]
Duplicate https://github.com/TerraFirmaGreg-Team/Modpack-Modern/issues/269
