### ISSUE TITLE
Исправление интегральной схемы при крафте кирпичей

### ISSUE THREAD

**Issue by Redangys** [TerraFirmaGreg-Team/Modpack-Modern#324]
### Версия модпака.

последняя

### Связанная проблема

![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/158020860/6bda1a2f-5ba8-48f3-850f-85e0130fedd9)
Крафт в сборщике требует 1 для акведука и 0 для кирпича

### Ваше решение

Поменять их местами так чтобы кирпич был на 1, а акведук на любое другое число интегральной схемы

**Comment by FriendlyCube** [comment]
проблема в том что не желательно чтобы в крафте использовалась схема "0"?

**Comment by Redangys** [comment]
Да, так как постоянно ходить и менять эту схему в сборщике оч много времени тратит
