### ISSUE TITLE
Allow crushing ore items with hammer after mining with picakxe

### ISSUE THREAD

**Issue by Jayx20** [TerraFirmaGreg-Team/Modpack-Modern#325]
### Version modpack Used

0.7.2

### Related Problem

To get crushed ore in the early game, you have to break the ore block with a hammer. As an example I wanted to get gem dust, so I mined some amethyst with my pickaxe.

Later I realized I can't crush the ore that I have:
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/38543604/99815f9d-e2a2-4b11-9e35-c988abd6f483)

You can do this with a crushing wheel or forge hammer, but not crafting with a normal hammer. It's possible for me to go back and mine more ore with my hammer, but I already mined most of the amethyst.

I also noticed for metals, the crushed ore is a lot better than the ore itself. I figured maybe i'm supposed to mine ore with the hammer, but I like to use the pickaxe (and greg mining hammer, which counts as a pickaxe). So I wonder if I am getting less ore by using the pickaxe and if that's intented.
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/38543604/c643ffb4-a265-4802-9142-d57aac80a0d7)

### Your Solution

My solution is just to add recipes to crush the ore items into dust either in the crafting grid with the hammer or in the quern. These recipes could be less rewarding them the crushing wheel or forge hammer recipes, to make them match the amount of metal you get from the ore.

**Comment by BabBimmaBome** [comment]
yeah we had this 1.12 idk why it isnt in 1.20

**Comment by Exzept1on** [comment]
Fixed in dev
