### ISSUE TITLE
Добавить в сборку Advanced Peripherals

### ISSUE THREAD

**Issue by ExpectoAmogus** [TerraFirmaGreg-Team/Modpack-Modern#337]
### Версия модпака.

0.7.2

### Связанная проблема

Слабый функционал периферии в CC : Tweaked

### Ваше решение

Добавить мод на расширенный функционал периферии для CC : Tweaked [Advanced Peripherals](https://www.curseforge.com/minecraft/mc-mods/advanced-peripherals)

**Comment by V-asakot** [comment]
Поддерживаю, крутая была бы фича

**Comment by C0ffo** [comment]
А что он добавляет?Чет полазил а непонял какие возможности предоставляет

**Comment by V-asakot** [comment]
Считывание nbt блоков(стандартный cc не позволяет), интеграция с ae2, считывание чата и запись в чат, черпашка со сканером блоков, сканер игроков, черепашка с чанклоудером(наверное отключат для сервера карфт,но я в сингле играю), доступ к инвентарю игрока(сразу успокою что не получится  объюзить против других игроков), дополненная реальность AR. Там есть другие фичи, но я перечислил что мне приглянулось.

**Comment by Exzept1on** [comment]
Добавлен

**Comment by V-asakot** [comment]
Мод будет не в 0.7.4, а далее?

**Comment by FriendlyCube** [comment]
его нету
