### ISSUE TITLE
Pots don't evaporate Sea Water

### ISSUE THREAD

**Issue by CopperCrusader** [TerraFirmaGreg-Team/Modpack-Modern#350]
### Version modpack Used

0.7.8

### Environment

Open to LAN

### New Worlds

Yes

### Expected Behavior

Pots should evaporate TerraFirmaCraft "Sea Water" (625mB) into GregTech "Small Pile of Salt".
![2024_05_05_16_55_26_TerraFirmaGreg_1 20 1](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/59585445/d9276096-5205-43e1-b41f-8239a7c6b53f)

### Actual Behavior

Despite the existence of a recipe for it, pots don't evaporate TerraFirmaCraft "Sea Water" into GregTech "Small Pile of Salt".
![2024_05_05_16_51_45_TerraFirmaGreg_1 20 1](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/59585445/e1d2e456-30f2-47ab-9512-2c7042bdf5c1)

### Steps to Reproduce

I've tried boiling it for multiple days (both Dark Red and Bright Red heat) but nothing ever seems to happen.
![2024_05_05_16_51_45_TerraFirmaGreg_1 20 1_2](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/59585445/5dafd171-802e-48b9-a3f1-4467756788f7)

**Comment by Kied22** [comment]
I found an easy fix for anyone stumbling on this with the same problem (in windows you can use right click > edit to make this change, just ctrl + f "salt" to find the code if you can't navigate by line).

Relevant File Path:
```TerraFirmaGreg-1.20.x-0.7.12-cf\minecraft\kubejs\server_scripts\tfc\recipes.js```

line 3074 contains the code for the salt water pot recipe shown below
![image](https://github.com/user-attachments/assets/77684840-a2cf-48c7-ac84-bbe699e0ef1b)

I wanted to make some other tweaks and fix this and discovered that duration is set by integer 300 and minimum boiling temperature is set by float 1000. They are either incorrectly swapped or, more likely that the float is off by an OoM (extra 0), resulting in the recipe being implemented but the temperature is impossible to achieve using wood fuel for a pot.

Changing this this will fix it but still requires exactly 625mB of water or it will not work

A better fix would be this (note: I also changed the output to be the full salt dust that can be used in the quern):
![image](https://github.com/user-attachments/assets/53b3d10c-39c2-4ccd-9128-3d85189c3e61)

**Comment by hron84** [comment]
I suggest you to check TFC Artisan recipes how they implemented, they actually generating TFC salt from salt water (1 per 200 mb of salt water). Also I suggest you to create TFC salt instead, it is more compatible with other TFC mods and you can easily recraft it to GT salt from quern -> small piles -> craft 2x2 -> GT salt.

**Comment by Exzept1on** [comment]
implemented
