### ISSUE TITLE
[Question] When will TFC trims be implemented?

### ISSUE THREAD

**Issue by chemlzh** [TerraFirmaGreg-Team/Modpack-Modern#353]
### Your Question

I inspected recent changes of TFG, and found that you have added modifications of TFC trims. However, both the smithing table and trim template still cannot be used. Meanwhile, I tried to bring TFC trims into TFG in 0.7.2 with upgraded TFC, but some errors still exist, since vanilla trim material like diamond will make TFC armor lose their texture. So do you figure out how to solve it? And when will TFC trims be implemented?

**Comment by Exzept1on** [comment]
Later of course, for now - no time

**Comment by Exzept1on** [comment]
Implemented in 0.8.0
