### ISSUE TITLE
Add supplementaries

### ISSUE THREAD

**Issue by KolxozGG** [TerraFirmaGreg-Team/Modpack-Modern#357]
### Version modpack Used

0.7.8

### Related Problem

Add Supplementaries and TFC Supplementaries mod, if possible

### Your Solution

Just add TFC Supplementaries with original supplementaries mod

**Comment by BabBimmaBome** [comment]
No

**Comment by Exzept1on** [comment]
TFC Supplementaries only exists for 1.18
