### ISSUE TITLE
Невозможно скрафтить некоторые предметы в ассемблере из-за ограничения стака тфк

### ISSUE THREAD

**Issue by Exzept1on** [TerraFirmaGreg-Team/Modpack-Modern#361]
### Version modpack Used

Любая

### Environment

Singleplayer, Multiplayer

### New Worlds

No

### Expected Behavior

.

### Actual Behavior

.

### Steps to Reproduce

.

**Comment by FriendlyCube** [comment]
доп инфа
в этом крафте в итоге выходит (насколько я помню) 32 айтема из-за ограничения стака 
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/112543401/fee476ad-5fa4-4040-a8bd-bd02bfa22bd8)
id: gtceu:assembler/long_distance_item_pipe

**Comment by mgun82** [comment]
Такая же проблема. Не могу сделатьпредметный трубопровод.

**Comment by Exzept1on** [comment]
Исправил в 0.8.0, но это требует комплексного решения, занесу в заметки, а пока закрою это
