### ISSUE TITLE
[Bug] When electronic tools run out their durability, the tool breaks up without returning any power unit

### ISSUE THREAD

**Issue by chemlzh** [TerraFirmaGreg-Team/Modpack-Modern#365]
### Version modpack Used

0.7.8

### Environment

Singleplayer

### New Worlds

Yes

### Expected Behavior

When a electronic tool ran out of its durability, it returns a energy unit with the same charge.

### Actual Behavior

When I use a electronic chainsaw with <1% durability to cut down a tree, it just totally broke up, and nothing returned to me (except for logs).

### Steps to Reproduce

Use a electronic chainsaw with low durability to cut down trees, until the durability used up.

### Additional Information

I have communicate with GTM groups, and they said in pure GTM, the power unit did return to player, therefore it must be caused by something stopping the break event before GT gets to it. I guess this bug may be related to Panda's Falling Tree's, but I don't have enough evidence. @Exzept1on 

https://github.com/GregTechCEu/GregTech-Modern/issues/1283

**Comment by Exzept1on** [comment]
blyat, why :(

**Comment by BabBimmaBome** [comment]
the gregtech were using still hasnt fixed the issue of chainsaw using durability and not power for trees. So maybe this isnt them after all

**Comment by BabBimmaBome** [comment]
if these 2 things are related

**Comment by chemlzh** [comment]
> ### Version modpack Used
> 0.7.8
> 
> ### Environment
> Singleplayer
> 
> ### New Worlds
> Yes
> 
> ### Expected Behavior
> When a electronic tool ran out of its durability, it returns a energy unit with the same charge.
> 
> ### Actual Behavior
> When I use a electronic chainsaw with <1% durability to cut down a tree, it just totally broke up, and nothing returned to me (except for logs).
> 
> ### Steps to Reproduce
> Use a electronic chainsaw with low durability to cut down trees, until the durability used up.
> 
> ### Additional Information
> I have communicate with GTM groups, and they said in pure GTM, the power unit did return to player, therefore it must be caused by something stopping the break event before GT gets to it. I guess this bug may be related to Panda's Falling Tree's, but I don't have enough evidence. @Exzept1on
> 
> [GregTechCEu/GregTech-Modern#1283](https://github.com/GregTechCEu/GregTech-Modern/issues/1283)

Bug confirmed with command used

![2024-05-21_23 57 45](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/32123043/63bae905-f9a6-4896-a223-5d41362ea0b0)

![2024-05-21_23 58 06](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/32123043/84d490e9-271b-4920-b6fa-1fecc8490b8e)

**Comment by chemlzh** [comment]
> the gregtech were using still hasnt fixed the issue of chainsaw using durability and not power for trees. So maybe this isnt them after all

I have discussed with GTM group, and they still haven't pull the fix.

**Comment by BabBimmaBome** [comment]
> > the gregtech were using still hasnt fixed the issue of chainsaw using durability and not power for trees. So maybe this isnt them after all
> 
> I have discussed with GTM group, and they still haven't pull the fix. Idk why.

crazy i reported this over 2 months ago

**Comment by chemlzh** [comment]
> > > the gregtech were using still hasnt fixed the issue of chainsaw using durability and not power for trees. So maybe this isnt them after all
> > 
> > 
> > I have discussed with GTM group, and they still haven't pull the fix. Idk why.
> 
> crazy i reported this over 2 months ago

GTM groups are too busy to pull the fix. I have asked one of the member. After all, they are trying to port features from GTCEu 1.12.2 and fix existed bugs.

**Comment by Exzept1on** [comment]
Fixed by GT devs
