### ISSUE TITLE
Complementary Shaders removing ore texture from gregtech ores

### ISSUE THREAD

**Issue by Flurbenhurgen** [TerraFirmaGreg-Team/Modpack-Modern#376]
### Version modpack Used

0.79

### Environment

Singleplayer

### New Worlds

Yes

### Expected Behavior

I would expect to be able to see GregTech ores.

### Actual Behavior

Ore veins from GregTech ore blocks are removed
![2024-05-31_15 50 54](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/29165919/c480c9b9-8497-4988-896f-7d5cae2bcd06)
![2024-05-31_15 54 26](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/29165919/68f8fe57-bab7-4e50-a7c6-b08a743fc12c)

### Steps to Reproduce

Install and enable complementary shaders
look at any GregTech ore block

**Comment by BabBimmaBome** [comment]
Works on my machine

**Comment by Exzept1on** [comment]
![image](https://github.com/user-attachments/assets/b9d2d78a-0136-4748-a97b-5bd7262135fa)

Maybe this was fixed in the some GT update. Fixed in dev.
