### ISSUE TITLE
После обновления сборки с версии 0.7.2 на любую более новую Alternator перестал генерировать энергию

### ISSUE THREAD

**Issue by Thomasx0** [TerraFirmaGreg-Team/Modpack-Modern#379]
### Версия модпака.

0.7.9

### Среда запуска

Одиночная игра

### Новые миры

Да

### Ожидаемое поведение

Доброго дня.
Собственно сабж, после обновы на любую версию выше 0.7.2 Alternator перестал генерировать энергию, у него постоянно режим работы Idle. Если откатится назад все работает.
Проблема возникает что уже в старом мире после обновы, и в новом созданном.

Должно быть так
Скрин с 0.7.2
![изображение](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/153584223/fe4421f8-e3ca-4be3-b269-68b28b5f5875)
![изображение](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/153584223/6ad38e38-ce89-421e-932b-53ef061d9b31)

### Фактическое поведение

Alternator при подаче кинетической энергии Create должен выдавать энергию, но в место этого у него постоянно режим работы Idle(Ожидание) 
Скрин с 0.7.9
![изображение](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/153584223/650a272d-869a-46b0-94b1-3d93adc377c8)
![изображение](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/153584223/d33d7c20-2d30-434f-a864-71aa85958e88)

### Действия по воспроизведению

Построить структуру, подать кинетик энергию вращения

**Comment by Thomasx0** [comment]
Баг пофиксили в GregTechCEu 1.20.1-1.3.0, генератор возобновил свою работу. Жду обновы.

**Comment by Exzept1on** [comment]
Исправлено в dev (благодаря обнове грега + исправлениям для мультиблока)
