### ISSUE TITLE
Add Sewing Kit mod

### ISSUE THREAD

**Issue by caelansimms** [TerraFirmaGreg-Team/Modpack-Modern#380]
### Version modpack Used

0.7.9

### Your Solution

Use of a Sewing Kit table (seperate from that of the Sewing Tables supplied by TFC base mod) for use for crafting leather armor, saddles, leather flasks, tool belt and tool belt pouches, backpacks, etc, to replace the need for leather knapping.

**Comment by ArcWielder** [comment]
Yes please leather knapping is kinda bad

**Comment by FriendlyCube** [comment]
https://www.curseforge.com/minecraft/mc-mods/sewing-kit
идея нравиться, немного усложнить крафт брони и рюкзака. чду одобрения глав админов
I like the idea of ​​making the crafting of armor and backpack a little more complicated. I look forward to the approval of the heads of admins
