### ISSUE TITLE
не работает сыродутный горн

### ISSUE THREAD

**Issue by qwertyasd12379** [TerraFirmaGreg-Team/Modpack-Modern#383]
### Версия модпака.

0.7.9

### Среда запуска

одиночка

### Новые миры

Да

### Ожидаемое поведение

при бросании предметов в сыродутку они образуют должны образовывать как бы типо блоков

### Фактическое поведение

но когда я кидаю придметы они просто там лежат все делал строил по гайдам TFC и из вики. в других мирах делал использовал любую железную руду уголь но ничего не помогает просто оставалось все в предметах

### Действия по воспроизведению

просто построить горн и кинуть руду да уголь я не знаю вдруг у меня какие то проблеиы с майном

**Comment by WaterMelwin** [comment]
cheese machine iron coal?
still on 0.7.9?

**Comment by qwertyasd12379** [comment]
> железный уголь для приготовления сыра? все еще в версии 0.7.9?

я не понял? что именно ты спрашиваешь?

**Comment by FriendlyCube** [comment]
>  все еще в версии 0.7.9?
 новейшая версия сборки 0.8.12

**Comment by FriendlyCube** [comment]
ты говоришь про это?
![image](https://github.com/TerraFirmaGreg-Team/Modpack-Modern/assets/112543401/5e2c5c26-1839-48ac-8d77-0b6e0e71b229)

**Comment by FriendlyCube** [comment]
> cheese machine iron coal? still on 0.7.9?

"used any iron ore and coal"
"cheese machine" I think it's a bloomery
