### ISSUE TITLE
Если у предмета осталась последняя прочность и им сломать руду, то она не выпадет

### ISSUE THREAD

**Issue by ppovolotsky** [TerraFirmaGreg-Team/Modpack-Modern#384]
### Версия модпака.

0.7.12

### Среда запуска

Одиночная игра

### Новые миры

Да

### Ожидаемое поведение

Ломал каменным молотом руду чтобы получить дробленую

### Фактическое поведение

При ломании молотом на последней единице прочности вместо дробленой руды падает так если бы блок ломали киркой

### Действия по воспроизведению

Взял каменный молот, довел прочность до минимума (еще что-то им разбить и он сломается), сломал блок руды и выпало сырье, вместо дробленой руды

### Дополнительная информация

Столкнулся в одиночной игре, сервер не проверял пока что

**Comment by REVISIONOFF** [comment]
Бро, это старый баг, которому уйма лет. И какой толк его фиксить? Ты часто попадаешь в такую ситуацию?

**Comment by ppovolotsky** [comment]
> Бро, это старый баг, которому уйма лет. И какой толк его фиксить? Ты часто попадаешь в такую ситуацию?

На начальном этапе пока каменные инструменты, если повезло найти руду удобно то мальца раздражает, я бы его отнес в минорные и повесил где-нибудь в дальнем углу трекера

**Comment by REVISIONOFF** [comment]
> > Бро, это старый баг, которому уйма лет. И какой толк его фиксить? Ты часто попадаешь в такую ситуацию?
> 
> На начальном этапе пока каменные инструменты, если повезло найти руду удобно то мальца раздражает, я бы его отнес в минорные и повесил где-нибудь в дальнем углу трекера

Согласен, добыча руды молотом очень упрощает добычу. Баг, наверное на стороне майна, т.к. не первый раз его вижу в различных модах (тот же ex nihilo и его молот и тому подобные моды), но он не настолько часто встречается, да и тем более руду ты получаешь

**Comment by Exzept1on** [comment]
Проблема где-то в LootJS, потому что если отключить модифаеры из него, то все работает как нужно, разберемся позже.
Работает как с киркой, так и с молотом.

**Comment by Exzept1on** [comment]
Fixed in dev
