### ISSUE TITLE
обновил фордж и перестало заппускаться

### ISSUE THREAD

**Issue by stornadok2** [TerraFirmaGreg-Team/Modpack-Modern#393]
### Версия модпака.

0.7.12

### Среда запуска

Запуск игры

### Новые миры

Да

### Ожидаемое поведение

Что оно запуститься

### Фактическое поведение

Не запусксм

### Действия по воспроизведению

обновил фордж и перестало запускаться

**Comment by TDumpling** [comment]
Зачем обновил?

**Comment by Kastodio** [comment]
Ставь сборку подчистую

**Comment by Exzept1on** [comment]
Ну не обновляй фордж значит, все равно там изменений практически нет

**Comment by stornadok2** [comment]
удалил modernfix, помогло

**Comment by Exzept1on** [comment]
обновил, модерн фикс и тоже заработало
