### ISSUE TITLE
Команда /enderchest

### ISSUE THREAD

**Issue by REVISIONOFF** [TerraFirmaGreg-Team/Modpack-Modern#405]
### Версия модпака.

0.7.12

### Среда запуска

Одиночная игра

### Новые миры

Да

### Ожидаемое поведение

Я думаю, что эта команда не должна быть доступна без читов

### Фактическое поведение

При ввое команды открывается читерский "рюкзак" ввиде эндер сундука, доступный везде и без включенных в игровом мире читов всяких колец, предметов и тому подобное, которые разрешали бы ввод этой команды.

### Действия по воспроизведению

/enderchest

### Дополнительная информация

Это не совсем сбой, но я думаю, что так явно не должно быть.

**Comment by Exzept1on** [comment]
Интересно, разраб какого говномода, добавил эту прекрасную команду

**Comment by Beethoven-n** [comment]
Please revert this regression. The experience of the early game is brutal without this feature. Yes, it's a cheat, but this is a *video game.*

This pack has hit the point where you have to cheat for the game to be bearable. I don't play this pack to play a rage game, I play it for the satisfaction of progression.

**Comment by WaterMelwin** [comment]
> Please revert this regression. The experience of the early game is brutal without this feature. Yes, it's a cheat, but this is a _video game._
> 
> This pack has hit the point where you have to cheat for the game to be bearable. I don't play this pack to play a rage game, I play it for the satisfaction of progression.

make make a large vessel
