### ISSUE TITLE
Настил для сушки

### ISSUE THREAD

**Issue by REVISIONOFF** [TerraFirmaGreg-Team/Modpack-Modern#407]
### Ваш вопрос

Очень странная вещь, если учитывать, что уникальных крафтов (и то, условно-бесполезных) пару штук, сушатся предметы (условно, кирпичи)(с не уникальными крафтами) также как и на земле, вмещают 1 предмет на 1 лист и соответственно 1 блок свободного пространства. Я не знаю, думаю, что на них предметы должны как минимум сушиться быстрее. (возможно баг, но вышесказанного не отменяет)

**Comment by REVISIONOFF** [comment]
> ### Ваш вопрос
> Очень странная вещь, если учитывать, что уникальных крафтов (и то, условно-бесполезных) пару штук, сушатся предметы (условно, кирпичи)(с не уникальными крафтами) также как и на земле, вмещают 1 предмет на 1 лист и соответственно 1 блок свободного пространства. Я не знаю, думаю, что на них предметы должны как минимум сушиться быстрее. (возможно баг, но вышесказанного не отменяет)
![image](https://github.com/TerraFirmaGreg-Team/Modpack-Modern/assets/160698337/b77b9307-f909-434f-90f2-2d18200a62ee)
Я просто... Не спрашивайте

**Comment by FriendlyCube** [comment]
в чем вопрос?
это чистая механика тфк, если нужно пофиксить время ожидание или кол-во вмещаемых предметов, то пиши issue в гит разрабов тфк
