### ISSUE TITLE
Empty Steel Cell recipe is broken

### ISSUE THREAD

**Issue by suzushiro226** [TerraFirmaGreg-Team/Modpack-Modern#409]
### Version modpack Used

0.7.12

### Environment

Singleplayer

### New Worlds

Yes

### Expected Behavior

Crafting an Empty Steel Cell requires a minimum of 4 pieces of steel.

### Actual Behavior

Steel is not used.
![image](https://github.com/TerraFirmaGreg-Team/Modpack-Modern/assets/84512237/0fbc1496-17a1-4d70-9815-1cfc1e9057db)

### Steps to Reproduce

Created a new instance with "TerraFirmaGreg-1.20.x-0.7.12-mmc.zip" and checked the recipe in the new world.

### Additional Information

There is no issue in Multiplayer.
![image](https://github.com/TerraFirmaGreg-Team/Modpack-Modern/assets/84512237/b79c03e0-fc9c-4e52-b3c4-97412b649ae4)

**Comment by suzushiro226** [comment]
Regardless of the recipe displayed, the correct ingredients need to be put in.
 the EMI recipe view appears to be broken.

**Comment by FriendlyCube** [comment]
![image](https://github.com/TerraFirmaGreg-Team/Modpack-Modern/assets/112543401/d0cea9ed-e7e3-48d8-b00c-fa7267ff7347)
There is no bug in the new version
