### ISSUE TITLE
Доп квест огнеупорной глины в ULV эре

### ISSUE THREAD

**Issue by SverhRazum-Nah** [TerraFirmaGreg-Team/Modpack-Modern#413]
### Версия модпака.

0.7.12

### Ваше решение

Добавить квест знакомящий игрока с возможностью получения огнеупорного кирпича на более поздних стадиях без необходимости гриндить каолинит и графит
![image](https://github.com/TerraFirmaGreg-Team/Modpack-Modern/assets/174268545/7e70c098-5f5d-4ae2-a649-114b4f2c9ecd)

**Comment by Kastodio** [comment]
На более поздних этапаха ? Так Каолин после каменного века и не нужен

**Comment by SverhRazum-Nah** [comment]
> На более поздних этапаха ? Так Каолин после каменного века и не нужен

ну в плане в начале пара. Тк каолинит очень долго копать, а для сталеварной печи надо много кирпичей. Не думаю что все её сразу же полную строят.

**Comment by FriendlyCube** [comment]
я не думаю что в этом квесте есть необходимость, @Xikaro переубеди меня если сможешь

**Comment by SverhRazum-Nah** [comment]
> я не думаю что в этом квесте есть необходимость, @Xikaro переубеди меня если сможешь

ну, можно во всяком случае добавить где то в описании квеста, или просто чисто квест на один шамотный кирпич, описание могу сам расписать. Но не настаиваю

**Comment by FriendlyCube** [comment]
этого крафта не будет в след обновлении
