### ISSUE TITLE
Щедрые квесты

### ISSUE THREAD

**Issue by SverhRazum-Nah** [TerraFirmaGreg-Team/Modpack-Modern#416]
### Версия модпака.

0.7.12

### Среда запуска

одиночная игра

### Новые миры

Не уверен

### Ожидаемое поведение

Награду за квест как и написано
![image](https://github.com/TerraFirmaGreg-Team/Modpack-Modern/assets/174268545/83149aa1-fc45-45d8-9255-4a3b09111b1a)

### Фактическое поведение

награды нет((

### Действия по воспроизведению

зайти в квесты)

**Comment by Lollovader** [comment]
EN : The questbook is not completed yet, and all of the quests in the LV chapter and after are temporairly taken from another modpack just to give players a baseline for progression. So if some quests may say that they will give you a reward, its a side effect of the copying.
They will be written properly in the future, but they'll probably not give any rewards.

**Comment by Exzept1on** [comment]
Наград не будет, нужно иногда пострадывать, и да квесты еще не завершены, поэтому вот такое встречается

**Comment by SverhRazum-Nah** [comment]
> Наград не будет, нужно иногда пострадывать, и да квесты еще не завершены, поэтому вот такое встречается

Если хочешь можешь мне файлов покидать где надо могу перевести. Не машинно, английский нормально понимаю

**Comment by Exzept1on** [comment]
можешь везде :)

> > Наград не будет, нужно иногда пострадывать, и да квесты еще не завершены, поэтому вот такое встречается
> 
> Если хочешь можешь мне файлов покидать где надо могу перевести. Не машинно, английский нормально понимаю
