### ISSUE TITLE
Недосмотр в крафте кнопок

### ISSUE THREAD

**Issue by SverhRazum-Nah** [TerraFirmaGreg-Team/Modpack-Modern#418]
### Версия модпака.

0.7.12

### Среда запуска

одиночная игра

### Новые миры

Да

### Ожидаемое поведение

Крафты кнопок почти из всего дерева:
![image](https://github.com/TerraFirmaGreg-Team/Modpack-Modern/assets/174268545/fab7eae6-3025-4b93-a02e-3823ddd4a47d)

### Фактическое поведение

Крафт кнопок из каучука и обработанной древесины:
![image](https://github.com/TerraFirmaGreg-Team/Modpack-Modern/assets/174268545/aa91f31a-b645-4ff6-b88c-b6a2f991a2b5)
![image](https://github.com/TerraFirmaGreg-Team/Modpack-Modern/assets/174268545/663875ce-9c1d-45e6-86de-8945c22398ff)

### Действия по воспроизведению

открыл EMI )

**Comment by Exzept1on** [comment]
Закрыто

**Comment by Exzept1on** [comment]
Правда там теперь из других прекрасных модов есть такие говно рецепты, но ничего, терпели тогда, потерпим и сейчас
