### ISSUE TITLE
Креозотовые доски можно повторно обработать в бочке с креозотом

### ISSUE THREAD

**Issue by Jeggor** [TerraFirmaGreg-Team/Modpack-Modern#419]
### Версия модпака.

0.7.12

### Среда запуска

Одиночная игра

### Новые миры

Да

### Ожидаемое поведение

Пропитанные креозотовые доски нельзя повторно обработать, дополнительный креозот не тратится

### Фактическое поведение

 В запечатанной бочке с креозотом процесс пропитывания начинается заново и идёт продолжается, пока не бочка не будет открыта или креозот не закончится

### Действия по воспроизведению

1) Наполнить бочку креозотом
2) Положить в неё достаточное количество креозотовых досок
3) Запечатать бочку

### Дополнительная информация

Причина: в рецепте указан тег "Доски". Креозотовые доски также попадают под этот тег, из-за чего процесс пропитывания продолжается.
Нужно как-то добавить креозотовые доски в исключение.
Плюс ещё локализация слетела (первый см. скриншот)
![image](https://github.com/user-attachments/assets/f3bf1076-eabd-424e-b02d-27236d53bdd7)
![image](https://github.com/user-attachments/assets/96b66ae8-54dd-4cc0-a11e-4f4265729d73)
![image](https://github.com/user-attachments/assets/96b66ae8-54dd-4cc0-a11e-4f4265729d73)

**Comment by FriendlyCube** [comment]
мде

**Comment by Endermanus** [comment]
Если исключить обработанные доски из forge:planks, то поломаются многие рецепты с данными досками. Добавить в блэклист ЧИСТО для этого рецепта нельзя. Тут уже надо будет создавать новый тэг (по типу tfg:treatable_planks или что-то наподобии)

**Comment by Exzept1on** [comment]
Ну дак круто же, дважды обработанные креозотовые доски!

**Comment by FriendlyCube** [comment]
решено фиксить не будем :D

**Comment by Endermanus** [comment]
Ну по сути логической ошибки нет (даже пропитанные доски могут что-то впитывать). Да и тем более это самый лёгкий способ избавиться от лишнего креозота

**Comment by Exzept1on** [comment]
Исправлено в недавнем обновлении GT. Но закрывать не буду, так как обнова еще не вышла.

**Comment by Exzept1on** [comment]
В греге починили
