### ISSUE TITLE
Possible Nether Integration

### ISSUE THREAD

**Issue by Lollovader** [TerraFirmaGreg-Team/Modpack-Modern#420]
### Version modpack Used

0.7.12

### Related Problem

One of the low priority objectives in the roadmap is to add the Nether

### Your Solution

https://github.com/eerussianguy/Beneath
https://github.com/eerussianguy/Beneath/releases
This mod add the integration between TFC and the Nether

### Additional Information

I may do a pull request in order to add all the ore gen stuff
Also more info about the mod can be found in the content tab called "Beneath" in the official TFC discord server

**Comment by FriendlyCube** [comment]
is there a link to the courseforge?

**Comment by Lollovader** [comment]
> is there a link to the courseforge?

No, the mod is relatively new and only has a github page, but it should already give a solid base for the nether

**Comment by Lollovader** [comment]
Also it allows structure gen so it could also be used for generating AE2 meteors, but thats probably better to do with a datapack

**Comment by WaterMelwin** [comment]
well cant put it in the modpack if it aint on curse

**Comment by FriendlyCube** [comment]
we can add only mods from course forge to our modpack

**Comment by Lollovader** [comment]
Got it, then ill either just wait for the mod to release or start doing some work

**Comment by Lollovader** [comment]
Just discovered that it's a data pack, is it still allowed?

**Comment by FriendlyCube** [comment]
@Xikaro

**Comment by Exzept1on** [comment]
funny

**Comment by iamrusskikh** [comment]
> funny

![image](https://github.com/user-attachments/assets/0fa2fc97-2510-4219-8549-cd461bd13cc9)

**Comment by Aspenhart** [comment]
Nether as a dimension doesn't fit a pack like TFG for a variety of reasons,
TFG is a realistic-ish pack, a hell dimension doesn't fit the theme this pack seems to be establishing. A better solution would be to get inspired by what Create: Astral did, and move Nether resources to The Moon, or give alternative ways to get them which don't involve the Nether.

Alternatively, The Nether could be turned into a planet. Removing the bedrock roof and tweaking the skybox a little would implement the nether while not breaking the immersion.

**Comment by WaterMelwin** [comment]
🤣
