### ISSUE TITLE
Официальному серверу TerraFirmaGreg в последние 3-4 дня стало плохо

### ISSUE THREAD

**Issue by Den666Bah666** [TerraFirmaGreg-Team/Modpack-Modern#421]
### Версия модпака.

0.7.12

### Среда запуска

официальный сервер TerraFirmaGreg

### Новые миры

Нет

### Ожидаемое поведение

Хороший tps как раньше

### Фактическое поведение

Почему-то в последнее время на сервере стал низкий tps. Частые выкидывания всех игроков с сервера и порой его перезапуска.

### Действия по воспроизведению

По случаю и случайности, но часто

### Дополнительная информация

Я не знаю вызвано ли это действиями какого-нибудь игрока с плохой систематизацией механизмов или проблема на стороне хосте, но всё равно считаю не лишним объявить о проблеме

**Comment by FriendlyCube** [comment]
ммммм нуууу ээээ нууу соответственно попытаюсь сделать всё что в моих силах

**Comment by Exzept1on** [comment]
Уже похорошело, отвечаю
