### ISSUE TITLE
Greenhouse Sprinkler irrigation

### ISSUE THREAD

**Issue by AryaElendril** [TerraFirmaGreg-Team/Modpack-Modern#428]
### Your Question

Hey there!

On my community server, users have begun to make the Greenhouse multiblock and are trying to understand how to irrigate their planters inside of it. As it is right now, the Pumping Station and all of the mechanical power items are disabled in the pack and there's no way to get water into the pipes to use with the sprinkler.

We've tried numerous setups using Create pipes and Gregtech pipes, but none of them are compatible with the sprinkler for us, so far.

What's the intended way of using the sprinkler system? Is this a bug or are we just not finding the proper setup?

**Comment by WaterMelwin** [comment]
you dont

**Comment by Exzept1on** [comment]
Fixed in dev
