### ISSUE TITLE
Добавить ТФК магме возможность греть бойлер

### ISSUE THREAD

**Issue by SverhRazum-Nah** [TerraFirmaGreg-Team/Modpack-Modern#430]
### Версия модпака.

0.7.12

### Связанная проблема

Магма из ТФК не греет бойлер, а обычную в мире не найти
![image](https://github.com/user-attachments/assets/14402d8b-7fd9-4b87-aef9-fb98e589241d)

### Ваше решение

Добавить магме из тфк тег на нагрев бойлера как у обычной магмы
![image](https://github.com/user-attachments/assets/ae21c610-b917-43fb-92b9-1bf3647026ca)

**Comment by Exzept1on** [comment]
Готово

**Comment by SverhRazum-Nah** [comment]
> Готово

Хорош
