### ISSUE TITLE
У этих модов вышли обновления, как часто они будут обновляться в сборке?

### ISSUE THREAD

**Issue by rogedkone** [TerraFirmaGreg-Team/Modpack-Modern#433]
### Ваш вопрос

![image](https://github.com/user-attachments/assets/4b82995c-2acf-4f10-96a3-47923c4dd938)

**Comment by Exzept1on** [comment]
Да я хоть щас бы обновил, правда я в отпуске, как и второй админ, так что расчилься, ща все отдохнем, может к тому времени и 1.21 тфк выйдет и нам всем станет хорошо

**Comment by rogedkone** [comment]
А, да не критично, в любом случае будет примерный список модов с которых можно начать) там FirmaCivilization как-то глобально обновилась, любопытно что будет на 1.21

**Comment by Exzept1on** [comment]
Уже обновлены
