### ISSUE TITLE
Нет крафта книги из ананасовой кожи

### ISSUE THREAD

**Issue by SverhRazum-Nah** [TerraFirmaGreg-Team/Modpack-Modern#436]
### Версия модпака.

0.7.12

### Среда запуска

одиночная игра

### Новые миры

Да

### Ожидаемое поведение

Наличие крафта из ананасовой кожи, как и в остальных крафтах
![image](https://github.com/user-attachments/assets/936f6ad6-ad9a-4cd1-b1ff-f3ca5dcfd2ba)

### Фактическое поведение

Крафт отсутствеут
![image](https://github.com/user-attachments/assets/b447c243-c1e6-4daf-b6d4-70a8afe42c05)

### Действия по воспроизведению

зайти в EMI

**Comment by Exzept1on** [comment]
Fixed
