### ISSUE TITLE
Reduce hazardous ore drops or damage

### ISSUE THREAD

**Issue by yuesha-yc** [TerraFirmaGreg-Team/Modpack-Modern#438]
### Version modpack Used

0.7.12

### Related Problem

Ores in andesite randomly drop Andesite dust for very high chance. Andesite dust contains hazardous materials, which kills you in poison in 3 seconds. This is so annoying when mining in early game, when there is absolutely no way to get hazardous protection suits. 

### Your Solution

Can you either remove the hazardous or decrease the damage amount or reduce its drop rate? Or make it preventable in some way? It just automatically enters your inventory and starts killing you.

**Comment by Endermanus** [comment]
You can just turn off poison for some materials in the config of GregTech.

**Comment by Moustik2002** [comment]
GT Config > Gameplay > Disable hazardous

**Comment by WaterMelwin** [comment]
Not tfg issue

**Comment by FriendlyCube** [comment]
Try increase hp

**Comment by Spacewielder** [comment]
If you break ore with a hammer, no dust will drop. It is also a good idea to break ore with a hammer anyway -especially with ores like chalcopyrite and tetrahedrite- because crushed ore will drop instead.

**Comment by WaterMelwin** [comment]
> Same with mining silver (required for blue steel) and lead. Some sort of early game protection gear would be really helpful. Like a cloth mask or using leather gloves or tongs. Something that's inconvenient or has low durability so the real hazmat suit is still desired, but makes mining those resources much less frustrating.

Not a tfg issue

**Comment by Pyritie** [comment]
> > Same with mining silver (required for blue steel) and lead. Some sort of early game protection gear would be really helpful. Like a cloth mask or using leather gloves or tongs. Something that's inconvenient or has low durability so the real hazmat suit is still desired, but makes mining those resources much less frustrating.
> 
> Not a tfg issue

It's a tfg issue because progression requires ores from hazardous veins a lot sooner than in normal gregtech and you can't easily mine around them because of cave-ins. It's an issue that comes up because of combining gt and tfc together - in their standalone mods these aren't issues.

Reducing friction between mods that weren't designed with each other in mind is absolutely a modpack issue.

**Comment by WaterMelwin** [comment]
again this isnt tfg issue its a gtcem issue

**Comment by Pyritie** [comment]
it's an issue because of tfc mechanics, therefore it's a tfg issue

**Comment by WaterMelwin** [comment]
god your brain dead

**Comment by G93d14** [comment]
> god your brain dead

friend it's never a good look to insult someone's intelligence just because they disagree with you. all it does is make you sound boorish.

but re: the hazard issue, the backpack prevents the hazards from poisoning you, and can be achieved even in the primitive stage, if you have found even one papyrus in your travels for kaolin. or if you've found some pumice and a few kelp flowers.

**Comment by yuesha-yc** [comment]
> > god your brain dead
> 
> 
> 
> friend it's never a good look to insult someone's intelligence just because they disagree with you. all it does is make you sound boorish.
> 
> 
> 
> but re: the hazard issue, the backpack prevents the hazards from poisoning you, and can be achieved even in the primitive stage, if you have found even one papyrus in your travels for kaolin. or if you've found some pumice and a few kelp flowers.

Does backpack automatically absorbs dropped materials? I think you need some auto pick upgrade?

**Comment by Pyritie** [comment]
> > > god your brain dead
> > 
> > 
> > friend it's never a good look to insult someone's intelligence just because they disagree with you. all it does is make you sound boorish.
> > but re: the hazard issue, the backpack prevents the hazards from poisoning you, and can be achieved even in the primitive stage, if you have found even one papyrus in your travels for kaolin. or if you've found some pumice and a few kelp flowers.
> 
> Does backpack automatically absorbs dropped materials? I think you need some auto pick upgrade?

You do, but it's not craftable until either LV or MV (I forget which, I remember it needed some kind of robot arms)

**Comment by G93d14** [comment]
backpack doesn't auto pick up, but if you throw the material into your backpack immediately it only gives you 9 seconds of poison which is better than being constantly poisoned at least.

come to think of it this might even be possible with just small vessels but I only ever went mining for lead after I got the backpack.

**Comment by WaterMelwin** [comment]
> > god your brain dead
> 
> friend it's never a good look to insult someone's intelligence just because they disagree with you. all it does is make you sound boorish.
> 
> but re: the hazard issue, the backpack prevents the hazards from poisoning you, and can be achieved even in the primitive stage, if you have found even one papyrus in your travels for kaolin. or if you've found some pumice and a few kelp flowers.

No point in just repeating shit over and over like that was going to go. Can't argue with stupid.

**Comment by jam-jar-binks** [comment]
> backpack doesn't auto pick up, but if you throw the material into your backpack immediately it only gives you 9 seconds of poison which is better than being constantly poisoned at least.
> 
> come to think of it this might even be possible with just small vessels but I only ever went mining for lead after I got the backpack.

unfortunately, you can also get andesite dust from mining zinc, a rather important early game material. and while putting it in vessels or backpacks almost works,  it can still kill you just by picking it up if your health is low. I'd argue that some sort of treated cloth mask that rapidly breaks would be an excellent addition to early gameplay.

**Comment by Exzept1on** [comment]
Fixed by greg
