### ISSUE TITLE
Краш игры при запуске

### ISSUE THREAD

**Issue by jlnx1** [TerraFirmaGreg-Team/Modpack-Modern#441]
### Версия модпака.

1.20.x - 0.7.12 - cf

### Среда запуска

одиночная игра

### С какой стороны краш

Клиент

### Новые миры

Нет

### Действия по воспроизведению

Запуск игры на Legacy Launcher

### Отчет о сбое

[tl-logger.txt](https://github.com/user-attachments/files/16660403/tl-logger.txt)
[latest.log](https://github.com/user-attachments/files/16660405/latest.log)
[debug.log](https://github.com/user-attachments/files/16660406/debug.log)

**Comment by Zapelmon** [comment]
Всё что я могу сказать, я пытался, он не запускается никаким образом. Как я понял из-за слишком новой версии фордж. Мой тебе совет, запусти на Tlaucnher, там оно хоть запустится. Но может быть проблема с невозможностью добыть солому каменным ножом, как у меня проблема.

**Comment by FriendlyCube** [comment]
Плохой ему совет даёшь, юзайте оба призму

**Comment by Zapelmon** [comment]
Вот то что мне ответили в моем обращении. Проблему решает: https://github.com/TerraFirmaGreg-Team/Modpack-Modern/issues/443#issuecomment-2297608786

**Comment by Zapelmon** [comment]
> Вот то что мне ответили в моем обращении. Проблему решает: [#443 (comment)](https://github.com/TerraFirmaGreg-Team/Modpack-Modern/issues/443#issuecomment-2297608786)

Решает проблему с запуском, но не с выпадением соломы. Буду переоткрывать свою ошибку

**Comment by Zapelmon** [comment]
> ### Версия модпака.
> 1.20.x - 0.7.12 - cf
> 
> ### Среда запуска
> одиночная игра
> 
> ### С какой стороны краш
> Клиент
> 
> ### Новые миры
> Нет
> 
> ### Действия по воспроизведению
> Запуск игры на Legacy Launcher
> 
> ### Отчет о сбое
> [tl-logger.txt](https://github.com/user-attachments/files/16660403/tl-logger.txt) [latest.log](https://github.com/user-attachments/files/16660405/latest.log) [debug.log](https://github.com/user-attachments/files/16660406/debug.log)
> 
> ### Дополнительная информация
> _No response_

Проблему с соломой решает. Просто нужно получить нож в выживании.
Советую попробовать и закрыть обращение.

**Comment by jlnx1** [comment]
Через призму работает
