### ISSUE TITLE
Rotten pumpkin is allowed to cut into fresh chunks

### ISSUE THREAD

**Issue by yuesha-yc** [TerraFirmaGreg-Team/Modpack-Modern#442]
### Version modpack Used

0.7.12

### Environment

Forge Server

### New Worlds

Yes

### Expected Behavior

Rotten pumpkin should not be allowed to cut into fresh chunks

### Actual Behavior

Rotten pumpkin is allowed to cut into fresh chunks

### Steps to Reproduce

Cut rotten pumpkin with knife.

### Additional Information

https://github.com/TerraFirmaGreg-Team/Modpack-Modern/blob/e2b09aafb6212de1c3dff9284e0bc49aae4b88b5/kubejs/server_scripts/tfc/recipes.js#L3054

**Comment by Exzept1on** [comment]
Fixed
