### ISSUE TITLE
Невозможно собрать солому каменным ножом

### ISSUE THREAD

**Issue by Zapelmon** [TerraFirmaGreg-Team/Modpack-Modern#443]
### Версия модпака.

0.7.12

### Среда запуска

Одиночная игра

### Новые миры

Да

### Ожидаемое поведение

Трава будет падать при ломании её каменным ножом, который делается из обтёски камня и палки.

### Фактическое поведение

При ломании им травы ничего не происходит, единственный способ это сломать траву ножом из greg(любым)

### Действия по воспроизведению

1) Установил сборку скачав mmc архив
2) Запустил сборку под Forge 47.2.6
3) Осознал тленность бытия от невозможности добыть солому
![TerraFirmaGreg 1 20 1 2024-08-19 22-15-23 (1)](https://github.com/user-attachments/assets/623de4f3-d568-4ee6-bb77-d44c84f1a76a)

### Дополнительная информация

Используется Tlaucncher, т.к по какой-то причине Legacy Launcher не может запустить эту сборку. Также невозможно запустить сборку с Cureforge в Legacy Laucncher, потому единственным выходом для запуска остался Tlauncher.
Проверял как на "Чистой" сборке, куда своих модов не добавлял, так и с дополнительными модами.

**Comment by Zapelmon** [comment]
> ### Версия модпака.
> 0.7.12
> 
> ### Среда запуска
> Одиночная игра
> 
> ### Новые миры
> Да
> 
> ### Ожидаемое поведение
> Трава будет падать при ломании её каменным ножом, который делается из обтёски камня и палки.
> 
> ### Фактическое поведение
> При ломании им травы ничего не происходит, единственный способ это сломать траву ножом из greg(любым)
> 
> ### Действия по воспроизведению
> 1. Установил сборку скачав mmc архив
> 2. Запустил сборку под Forge 47.2.6
> 3. Осознал тленность бытия от невозможности добыть солому
>    ![TerraFirmaGreg 1 20 1 2024-08-19 22-15-23 (1)](https://private-user-images.githubusercontent.com/58384970/359221673-623de4f3-d568-4ee6-bb77-d44c84f1a76a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwOTYyMzMsIm5iZiI6MTcyNDA5NTkzMywicGF0aCI6Ii81ODM4NDk3MC8zNTkyMjE2NzMtNjIzZGU0ZjMtZDU2OC00ZWU2LWJiNzctZDQ0Yzg0ZjFhNzZhLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDE5MzIxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5OTUwNjgwZThhZDY1ZDNhYTE5MTExZWU4ZWQ4YzRmZjU2YjVkMTg1NGU4YjZhMDc1YmVkNjE4NmQ5NDVlZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hTTwNzMmRWcsOa-d6earFVaCxylsnX2AGZfOU0UaZOA)
>          
>            [
>              
>                ![TerraFirmaGreg 1 20 1 2024-08-19 22-15-23 (1)](https://private-user-images.githubusercontent.com/58384970/359221673-623de4f3-d568-4ee6-bb77-d44c84f1a76a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwOTYyMzMsIm5iZiI6MTcyNDA5NTkzMywicGF0aCI6Ii81ODM4NDk3MC8zNTkyMjE2NzMtNjIzZGU0ZjMtZDU2OC00ZWU2LWJiNzctZDQ0Yzg0ZjFhNzZhLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDE5MzIxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5OTUwNjgwZThhZDY1ZDNhYTE5MTExZWU4ZWQ4YzRmZjU2YjVkMTg1NGU4YjZhMDc1YmVkNjE4NmQ5NDVlZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hTTwNzMmRWcsOa-d6earFVaCxylsnX2AGZfOU0UaZOA)
>              
>            ](https://private-user-images.githubusercontent.com/58384970/359221673-623de4f3-d568-4ee6-bb77-d44c84f1a76a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwOTYyMzMsIm5iZiI6MTcyNDA5NTkzMywicGF0aCI6Ii81ODM4NDk3MC8zNTkyMjE2NzMtNjIzZGU0ZjMtZDU2OC00ZWU2LWJiNzctZDQ0Yzg0ZjFhNzZhLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDE5MzIxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5OTUwNjgwZThhZDY1ZDNhYTE5MTExZWU4ZWQ4YzRmZjU2YjVkMTg1NGU4YjZhMDc1YmVkNjE4NmQ5NDVlZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hTTwNzMmRWcsOa-d6earFVaCxylsnX2AGZfOU0UaZOA)
>            
>            
>              
>                
>                  
>                
>                
>                  
>                  
>                
>              
>              [
>                
>                  
>                
>              ](https://private-user-images.githubusercontent.com/58384970/359221673-623de4f3-d568-4ee6-bb77-d44c84f1a76a.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwOTYyMzMsIm5iZiI6MTcyNDA5NTkzMywicGF0aCI6Ii81ODM4NDk3MC8zNTkyMjE2NzMtNjIzZGU0ZjMtZDU2OC00ZWU2LWJiNzctZDQ0Yzg0ZjFhNzZhLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDE5MzIxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5OTUwNjgwZThhZDY1ZDNhYTE5MTExZWU4ZWQ4YzRmZjU2YjVkMTg1NGU4YjZhMDc1YmVkNjE4NmQ5NDVlZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hTTwNzMmRWcsOa-d6earFVaCxylsnX2AGZfOU0UaZOA)
> 
> ### Дополнительная информация
> Используется Tlaucncher, т.к по какой-то причине Legacy Launcher не может запустить эту сборку. Также невозможно запустить сборку с Cureforge в Legacy Laucncher, потому единственным выходом для запуска остался Tlauncher. Проверял как на "Чистой" сборке, куда своих модов не добавлял, так и с дополнительными модами.

![Uploading TerraFirmaGreg 1.20.1 2024-08-19 22-15-23 (1).gif…]()

**Comment by Zapelmon** [comment]
Почему-то гифка не вставилась, вроде как:
![Uploading TerraFirmaGreg 1.20.1 2024-08-19 22-15-23 (1).gif…]()

**Comment by FriendlyCube** [comment]
Херня твоя "чистая сборка", лаунчер говно и нормально конфиги заюзать не может, меняй тл на норм лаунчер который может без проблем скачивать сборки и юзать их( то есть буквально любой кроме тл)

**Comment by FriendlyCube** [comment]
https://github.com/Diegiwg/PrismLauncher-Cracked держи ноом лаунчер

**Comment by FriendlyCube** [comment]
откуда ты установил модпак в призму?

**Comment by FriendlyCube** [comment]
пиши ник в дс там выяснять будем

**Comment by Zapelmon** [comment]
> пиши ник в дс там выяснять будем

eheh4148

**Comment by FriendlyCube** [comment]
https://discord.com/channels/400913133620822016/1134892736529584168 заходи

**Comment by Zapelmon** [comment]
Для будущих юзеров. Проблема решаете установкой призма лаунчера, установкой сборки через Curseforge **ВНУТРИ** призма лаунчера, и **СОЗДАНИЕМ НОЖА В ВЫЖИВАНИИ**
Надеюсь информация будет полезна юзерам что столкнутся с такой же проблемой.
