### ISSUE TITLE
Game Crashes when loading worldgen menu

### ISSUE THREAD

**Issue by ARG-DT** [TerraFirmaGreg-Team/Modpack-Modern#447]
### Version modpack Used

0.7.12

### Environment

Loading the worldgen menu (Singleplayer)

### Side Crashed

Client

### New Worlds

Yes

### Steps to Reproduce

You need to have Minecraft 1.20.1, Forge 47.3.5 and these mods:
	- ae2 15.2.2
	- alekiroofs 1.0.3
	- alekiships 1.0.10
	- architectury 9.2.14
	- cloth_config 11.1.118
	- create 0.5.1.f
	- curios 5.9.1+1.20.1
	- expatternprovider 1.20-1.1.12-forge
	- firmaciv 1.0.4
	- firmalife 2.1.6
	- forge 47.3.5
	- ftblibrary 2001.2.4
	- ftbquests 2001.4.8
	- ftbteams 2001.3.0
	- ftbxmodcompat 2.1.1
	- glodium 1.20-1.5-forge
	- gtceu 1.3.1
	- kubejs 2001.6.5-build.7
	- kubejs_create 2001.2.5-build.2
	- kubejs_tfc 1.2.0
	- patchouli 1.20.1-84-FORGE
	- puzzleslib 8.1.20
	- rhino 2001.2.2-build.18
	- tfc 3.2.7
	- tfcambiental 1.20.1-3.3.0
	- tfg 0.5.9

### Crash Report

[crash-2024-08-21_17.01.49-client.txt](https://github.com/user-attachments/files/16694433/crash-2024-08-21_17.01.49-client.txt)

I don't have the log right now sorry :(

### Additional Information

I had other problems with kubejs and other mods, so I was trying other versions of the mods. I solved the other issues by myself, but I can't get rid of this crash. Furthermore, I somehow managed to fix it, but when I put more mods it broke again, and I don't remember how I fixed it the first time. I just remember that it was a worldgen bug that I fixed, deleting the worldgen data of TFC and TFG inside kubejs carpet, but now is a different bug that I can't fix. I just know that kubejs is not the issue any more, instead it's a bug in TFG and Gregtechceu.

PD: I wana play TFG please help me :( i have been trying for weeks

**Comment by Exzept1on** [comment]
what? 0.7.12 is stable (if you have upgraded some mods by yourself, then there is nothing we can do to help you)

**Comment by ARG-DT** [comment]
I understand, I am trying to download the modpack again with the original mods.

**Comment by ARG-DT** [comment]
btw should i close the issue (i am sure it will crash again so it would be better to just update this issue)
