### ISSUE TITLE
Potassium Carbonate

### ISSUE THREAD

**Issue by Simon-R1** [TerraFirmaGreg-Team/Modpack-Modern#448]
### Version modpack Used

0.7.12

### Related Problem

The recipe for making potassium carbonate from hydroxide was removed, which makes the GCYR rockets uncraftable

### Your Solution

re-add the recipe from potassium hydroxide and create a centrifuge recipe from potash

**Comment by FriendlyCube** [comment]
This crafting recipe is not removed; it's not in the mod itself because the mod is not finished yet.

**Comment by Simon-R1** [comment]
It looks like they use the Gregtech recipe, which seems to be ported on the newest version

**Comment by Simon-R1** [comment]
Turns out it was a gtceu recipe, not a gregicallity rocketry one. For some reason it was overwritten on the pack recipe loader.
