### ISSUE TITLE
Alloy smelter red alloy recipe is wrong

### ISSUE THREAD

**Issue by jarmush** [TerraFirmaGreg-Team/Modpack-Modern#454]
### Version modpack Used

1.20.x-0.7.12

### Environment

Singleplayer

### New Worlds

Yes

### Expected Behavior

Alloy smelter should take 3 copper and 1 redstone to make 4 red alloy ingots

### Actual Behavior

Alloy smelter takes 3 redstone and 1 copper

### Steps to Reproduce

open the alloy smelter and try to make a red alloy ingot

**Comment by WaterMelwin** [comment]
umm no it takes 1 copper and 4 redstone as it always has

**Comment by WaterMelwin** [comment]
and it always has made 1

**Comment by jarmush** [comment]
so this recipe doesn't make sense because liquid red alloy recipe is 15-25% redsone and 75-85% copper
![image](https://github.com/user-attachments/assets/5767c0e7-86a6-49da-848a-eddc04e6045d)


Turning 4 ingots into 1 ingot in alloy smelter machine is obviously someone's config typo

**Comment by jarmush** [comment]
OMG, i've just noticed that alloy smelter machine consumes 5 ingots to make 1 red alloy ingot!
nonsense

**Comment by WaterMelwin** [comment]
Cry about it

**Comment by Exzept1on** [comment]
Works as intended.
