### ISSUE TITLE
Alternative Kaolinite Recipe

### ISSUE THREAD

**Issue by flatpop** [TerraFirmaGreg-Team/Modpack-Modern#455]
### Version modpack Used

0.7.12

### Related Problem

Kaolinite is one of the few resources that are exclusive to certain climates. Other climate specific resources like Kapok trees which can be moved and grown at a different location, kaolinite can require players to travel large distances for an extremely basic and vital resource.

### Your Solution

Add an alternative recipe to Kaolinite. I have made one based off the real world chemical composition of Kaolinite. This recipe is not designed to replace kaolinite mining, but provide a difficult alternative for players who don't want to or cannot travel far distances to find Kaolinite. 

The recipe is:
1 clay ball
1 aluminum dust
1 fullers earth (or silicon dust)
1 bone meal or calcium dust
1 of any sedimentary dust

Once again, this recipe is based on the real world chemical composition of fire clay/kaolinite.

If the devs do decide on implementing this recipe, I have already made it in KubeJS for your convenience.

  // Kaolin Crafting
	event.shapeless(
		Item.of('tfc:kaolin_clay', 1),
		[
			'minecraft:clay_ball',
			'gtceu:aluminium_dust',
			['gtceu:fullers_earth_dust', 'gtceu:silicon_dust', 'gtceu:silicon_dioxide_dust'],
			['minecraft:bone_meal', 'gtceu:calcium_dust'],
			['tfg:shale_dust', 'tfg:claystone_dust', 'tfg:limestone_dust', 'tfg:conglomerate_dust', 'tfg:dolomite_dust', 'tfg:chert_dust', 'tfg:chalk_dust']
		]
	)

**Comment by WaterMelwin** [comment]
or just go to where kaolin spawns

**Comment by flatpop** [comment]
> or just go to where kaolin spawns

thats an extremely insightful and helpful comment, i appreciate the time and dedication you put into crafting it

**Comment by WaterMelwin** [comment]
time it took you to write that whole post you could have dug up 20k kaolin clay

**Comment by Wyrmlet** [comment]
To be fair, this is less about this modpack and more about TFC in general, as the mod is trying to be realistic to a fault which doesn't always lead to the best player experience. An alternative recipe for fireclay would be great, as otherwise all of gregtech is locked behind RNG and hours of just walking.

**Comment by Pyritie** [comment]
On a related subject, some sort of hint about where to find graphite veins would be helpful - not only is it different from base TFC (so the TFC guidebook is wrong here), but there's nothing helpful besides "find gabbro, prop pick randomly, and pray".
Some kind of surface feature (a special flower, small ores, etc) would be a massive help.

**Comment by jam-jar-binks** [comment]
Ive had massive luck finding graphite in gabbro spots in basalt under the ocean. that seems to be a hotspot for spawning it.
And honestly, with how rare kaolin can be if you get unlucky (I have spent multiple days searching for it with people, and even now as  ive started tping around the map and using commands i cannot find any of the fucking stuff, even in biomes and climate where it should), some sore of alternative recipe would be nice.

**Comment by caelansimms** [comment]
> On a related subject, some sort of hint about where to find graphite veins would be helpful - not only is it different from base TFC (so the TFC guidebook is wrong here), but there's nothing helpful besides "find gabbro, prop pick randomly, and pray". Some kind of surface feature (a special flower, small ores, etc) would be a massive help.

Maybe use Tiny piles of Graphite dust as your marker on the surface? it would be the functional equivalent of small ores indicating the ore below it - how you go about implementing that, I don't know.

**Comment by Wyrmlet** [comment]
Piles of ores on the surface is actually a feature that GTCEu has by default and it is configurable like the ore veins themselves, but in this pack it seems to have been disabled on purpose.

**Comment by Beethoven-n** [comment]
seconded. at least spawn it in more of the biomes that coincide with plateau, old mountains and highlands.
biomes such as oceanic mountains, volcanic mountains, volcanic oceanic mountains, rolling hills, badlands, inverted badlands, canyons, etc.

**Comment by EpicOrange** [comment]
I think the decision to gate crucibles and blast furnaces behind kaolin is perfectly reasonable. As everybody knows, real world civilizations could not develop steel unless they lived near the kaolin mountains in China.

No, I fully support this alternative recipe idea. To be more constructive: if the idea is that you want stronger (refractory) clay for steelmaking, and you want realism, we got [other](https://en.wikipedia.org/wiki/Silicon_dioxide) [refractory](https://en.wikipedia.org/wiki/Aluminium_oxide) [material](https://en.wikipedia.org/wiki/Fuller%27s_earth) as suggested in the recipe above, we got [grog](https://en.wikipedia.org/wiki/Grog_(clay)), we got non-kaolin [ball clay](https://digitalfire.com/material/80). [Here's a guy making a small crucible from soil, toilet paper, and sodium silicate.](https://timtinker.com/diy-refractory-from-paper-and-sodium-silicate-born-in-fire-to-survive-in-fire/) Making kaolin+graphite the only refractory clay that exists, isn't that the less-realism choice?

**Comment by Pyritie** [comment]
> I think the decision to gate crucibles and blast furnaces behind kaolin is perfectly reasonable. As everybody knows, real world civilizations could not develop steel unless they lived near the kaolin mountains in China.
> 
> No, I fully support this alternative recipe idea. To be more constructive: if the idea is that you want stronger (refractory) clay for steelmaking, and you want realism, we got [other](https://en.wikipedia.org/wiki/Silicon_dioxide) [refractory](https://en.wikipedia.org/wiki/Aluminium_oxide) [material](https://en.wikipedia.org/wiki/Fuller%27s_earth) as suggested in the recipe above, we got [grog](https://en.wikipedia.org/wiki/Grog_(clay)), we got non-kaolin [ball clay](https://digitalfire.com/material/80). [Here's a guy making a small crucible from soil, toilet paper, and sodium silicate.](https://timtinker.com/diy-refractory-from-paper-and-sodium-silicate-born-in-fire-to-survive-in-fire/) Making kaolin+graphite the only refractory clay that exists, isn't that the less-realism choice?

I don't disagree with your assessment, but this part is also just how terrafirmacraft works, not something specific to TFG. Does TFC have its own github or place for suggestions?

**Comment by caelansimms** [comment]
https://github.com/TerraFirmaCraft/TerraFirmaCraft
There is also the TFC discord.

**Comment by Exzept1on** [comment]
Implemented
