### ISSUE TITLE
Steam extractor does not behave as Quest book advertises.

### ISSUE THREAD

**Issue by JumsAOMems** [TerraFirmaGreg-Team/Modpack-Modern#457]
### Version modpack Used

0.7.12 (1.20.x)

### Environment

Likely all

### New Worlds

Yes

### Expected Behavior

Putting TFC dirts in extractor results in bone meal, as per the quest book.

### Actual Behavior

Putting TFC dirts in extractor does nothing.

### Steps to Reproduce

1) Read the quest "Steam Extractor" in the steam age.
2) Note it says "You can also process Dirt in the extractor for Bones, ..."
3) Attempt to put any TFC dirt into the steam extractor.
4) Marvel as nothing happens.

### Additional Information

Probably either a recipe conflict, or just misinformation.

**Comment by WaterMelwin** [comment]
this isnt gregtech community pack sorry

**Comment by JumsAOMems** [comment]
I'm not sure what you mean by this.
Are you trying to be snide and sarcastic about a minor text inconsistency? Or is there some context I'm missing?

**Comment by WaterMelwin** [comment]
the quests are just ported from that modpack

**Comment by JumsAOMems** [comment]
Ah. Is it difficult to alter the text, or something? I'm unfamiliar with the quest book framework.

**Comment by WaterMelwin** [comment]
just hasnt been done yet

**Comment by JumsAOMems** [comment]
Then I'll just leave the issue up. Thanks for the info.

**Comment by Exzept1on** [comment]
#562
