### ISSUE TITLE
Add information to early quests to guide the player

### ISSUE THREAD

**Issue by Hexicube** [TerraFirmaGreg-Team/Modpack-Modern#458]
### Version modpack Used

1.20.x 0.7.12

### Your Solution

Almost all the quests for early game give little or no information on how to complete them, for instance I had to look up how to weld ingots as it's not in the GUI.

Since the quests are there purely for guidance they should explain how things work, like how the charcoal pit one does.

Semi-related: Kaolin clay quest blocks regular clay quest for no reason, I would expect clay to be a zero-dependency quest.

**Comment by Exzept1on** [comment]
![image](https://github.com/user-attachments/assets/98f1123e-6bf1-49b9-8c18-ac54db115f73)
