### ISSUE TITLE
High Pressure Steam Macerator

### ISSUE THREAD

**Issue by Superzocker99** [TerraFirmaGreg-Team/Modpack-Modern#459]
### Version modpack Used

0.7.12

### Environment

Singelplayer

### New Worlds

Yes

### Expected Behavior

Creosote-treated wood plank should turn into Treated wood pulp when put in the High pressure steam Macerator

### Actual Behavior

Nothing happens. The macerator does not accept the treated wood.

### Steps to Reproduce

Put Creosote-treated wood plank into High pressure Steam Macerator

### Additional Information

With the Basic macerator it is working. Is it intentional that it doesn't work with the Steam one?

**Comment by WaterMelwin** [comment]
stompid
