### ISSUE TITLE
Items not showing in JEI/EMI recipes

### ISSUE THREAD

**Issue by minecraftothersteve** [TerraFirmaGreg-Team/Modpack-Modern#461]
### Version modpack Used

0.7.12

### Environment

Singleplayer

### New Worlds

Yes

### Expected Behavior

Recipes in the JEI/EMI window should show all required ingredients

### Actual Behavior

Recipes in the JEI/EMI window are not displaying all of the required ingredients, and instead just show empty lots. I believe it's mostly happening with Gregtech machine recipes.
Sometimes reloading the game will fix it for some recipes, but not for all. Reloading can also cause other ingredients to not display (ie. a recipe may show item A but not item B, then after reload it would be the opposite with item B showing but not item A).
When viewing the recipe through the bookmark tooltip, all ingredients are properly displaying. The issue just seems to be with the main recipe window.
![image](https://github.com/user-attachments/assets/8a63eca7-9e4e-4466-8af9-b85e2832af04)
![image](https://github.com/user-attachments/assets/390f2d2a-fd6e-465d-bcc6-310c40c0a421)

### Steps to Reproduce

1. Open inventory and search for recipe
2. Left-click the item in the search results to view the recipe window

**Comment by minecraftothersteve** [comment]
Also seeing the issue in the EMI tree view. This section of the tree should include the 8 steel plate required to make the lv machine casing, but it's only showing the circuit below it. This then effects the total cost at the bottom, where it shows only 1 steel ingot is required, when in fact it needs an additional 8.
![image](https://github.com/user-attachments/assets/844f3ddd-48d9-49a0-9023-95c68ce5e2d2)

**Comment by minecraftothersteve** [comment]
Sorry, didn't mean to close the issue 🤦

**Comment by minecraftothersteve** [comment]
Sorry, didn't mean to close the issue 🤦

**Comment by FriendlyCube** [comment]
try downloading an older version of the EMI mod

**Comment by minecraftothersteve** [comment]
I have EMI v1.1.6. I just did a clean install of the pack using Prism and it also has 1.1.6. 
I'll make copies of the instance and try both 1.1.7 and 1.1.5, then report back

**Comment by FriendlyCube** [comment]
Prism's mod updater updated only EMI?

**Comment by minecraftothersteve** [comment]
Ya, in Prism I opened the mod list then right-clicked EMI and selected "Check for updates" so it only updated EMI. Nothing else was changed

**Comment by FriendlyCube** [comment]
okey, pls do not update mods or do it with caution because the modpack may break due to some updated mod

**Comment by minecraftothersteve** [comment]
Fair enough. When I get some time later I'll also try downgrading to a previous version of EMI like 1.1.5 like you suggested

**Comment by minecraftothersteve** [comment]
I just created a new instance of the pack and replaced EMI with 1.1.5, but it did not resolve the issue.

I took a look through EMI changelogs and issues, and I believe they fixed the issue in 1.1.7 https://github.com/emilyploszaj/emi/issues/534

My game with EMI 1.1.12 is working properly, so I'm going to continue playing with that knowing I may experience other EMI related issues

**Comment by Exzept1on** [comment]
Fixed in dev (by using last gt + last emi)
