### ISSUE TITLE
Create water wheels ought to work on flowing river water

### ISSUE THREAD

**Issue by nilederg** [TerraFirmaGreg-Team/Modpack-Modern#467]
### Version modpack Used

0.7.12

### Your Solution

Currently, the water wheels provided by Create work in the vanilla Flowing Water blocks, but not in the additional flat flowing water provided by TerraFirmaCraft that occurs in rivers. Seeing as, traditionally, water wheels were _only_ used in rivers, this feels like a significant issue. I would go as far as to say, if it is possible, that water wheels should only work in rivers, so as to minimize the loss of realism created by infinite water sources.

**Comment by Pyritie** [comment]
They work for me, can you post a screenshot of your setup?

**Comment by Exzept1on** [comment]
I think its works fine for me, closing this
