### ISSUE TITLE
Gregtech recipes from blue and red steel are the wrong way around

### ISSUE THREAD

**Issue by FabricatorZayac** [TerraFirmaGreg-Team/Modpack-Modern#469]
### Version modpack Used

0.7.12

### Environment

Forge server

### New Worlds

Yes

### Expected Behavior

In the gregtech mixer and alloy blast smelter
Red steel should take Rose Gold and Brass
Blue steel should take Sterling Silver and Bismuth Bronze

### Actual Behavior

Blue steel takes Rose Gold and Brass
Red steel takes Sterling Silver and Bismuth Bronze

### Steps to Reproduce

Look at the recipes in EMI

### Additional Information

Simple mistake somewhere in kubejs

**Comment by Exzept1on** [comment]
Not a mistake inside kjs, it gt feature
duplicate: https://github.com/TerraFirmaGreg-Team/Modpack-Modern/issues/422
