### ISSUE TITLE
Skin doesnt load on server

### ISSUE THREAD

**Issue by Cmonster820** [TerraFirmaGreg-Team/Modpack-Modern#475]
### Version modpack Used

0.7.12

### Environment

Forge Server

### New Worlds

Yes

### Expected Behavior

expected skin to be 
![Expected Skin](https://github.com/user-attachments/assets/baa2aca1-8730-4e46-8910-28f34c390438)

### Actual Behavior

My skin was 
![Actual Skin](https://github.com/user-attachments/assets/aac35e12-eccf-4cfc-aeab-b00b6a2cc14f)

### Steps to Reproduce

join server
notice skin is wrong
restart game several times and bug persists

### Additional Information

The server hosting site shows
![Server hosting site display](https://github.com/user-attachments/assets/e11038dd-3224-4cf9-8835-371842f15cd8)
and this bug does not exist on singleplayer

**Comment by WaterMelwin** [comment]
turn offline mode off

**Comment by Cmonster820** [comment]
I didn't realize that that was on, or that that could cause this issue, I will try that

**Comment by Cmonster820** [comment]
Thank you

**Comment by Tors-0** [comment]
for some reason offline mode is enabled by default with the server pack, i feel this should be changed
