### ISSUE TITLE
Crashes i think cause of mixin class or somethimg.

### ISSUE THREAD

**Issue by GhostDragon420** [TerraFirmaGreg-Team/Modpack-Modern#481]
### Version modpack Used

0.17.12

### Environment

Singleplayer

### Side Crashed

Unsure

### New Worlds

Yes

### Steps to Reproduce

I installed the pack by zip and by link from githun the 0.17.12 version and then try to start it.

### Crash Report

[terrafimagreg1.20.log.offline.txt](https://github.com/user-attachments/files/16983680/terrafimagreg1.20.log.offline.txt)
[terrafimagreg1.20.log.online.txt](https://github.com/user-attachments/files/16983681/terrafimagreg1.20.log.online.txt)

### Additional Information

i think its something to do with the mixing class and stuff or something is not reading right.

**Comment by GhostDragon420** [comment]
[offline.0.7.11.txt](https://github.com/user-attachments/files/16984247/offline.0.7.11.txt)
[Online 0.17.11.txt](https://github.com/user-attachments/files/16984248/Online.0.17.11.txt)

**Comment by Aleks59** [comment]
In logs I can see that you have wrong Java version. You using 22 but it should be 17.

**Comment by Exzept1on** [comment]
Use Java 17-21

**Comment by GhostDragon420** [comment]
ty
