### ISSUE TITLE
Leather Automation

### ISSUE THREAD

**Issue by antlersss** [TerraFirmaGreg-Team/Modpack-Modern#483]
### Version modpack Used

0.7.12

### Related Problem

There is no way to automate leather production. Create deployers cannot place soaked hides on logs, nor can they scrape hides already placed on logs. Additionally, the removal of scraped hide from logs would be very difficult to automate, with the two deployers needed to place and scrape hides already present.

### Your Solution

There are two possible solutions to this:
1. Add a recipe that uses GregTech machines to automatically process hides/soaked hides. I'm thinking it would be the macerator or cutter. If this option were to be taken, I would also add gregtech recipes for limewater and tannin (chemical bath), as well as the soaking, preparing, and tanning of hides (also chemical baths). 
2. Add the ability for Create deployers to place, scrape, and preferably automatically remove hides from scraping logs. This would leave the rather tedious barrel automation in, but it has its own charm to it.

**Comment by Pyritie** [comment]
AutoTerraFirmaCraft had a recipe for this, where a deployer holding a knife would do the scraping, if the modpack authors need any inspiration!

**Comment by Pyritie** [comment]
I made some recipes:

`	event.recipes.gtceu.cutter('tfg:unrefined_paper')
		.itemInputs('tfc:unrefined_paper')
		.itemOutputs('minecraft:paper')
		.duration(100)
		.EUt(16)
		
	event.recipes.gtceu.cutter('tfg:small_scraped_hide')
		.itemInputs('tfc:small_soaked_hide')
		.itemOutputs('tfc:small_scraped_hide')
		.duration(100)
		.EUt(16)
	
	event.recipes.gtceu.cutter('tfg:medium_scraped_hide')
		.itemInputs('tfc:medium_soaked_hide')
		.itemOutputs('tfc:medium_scraped_hide')
		.duration(100)
		.EUt(16)
	
	event.recipes.gtceu.cutter('tfg:large_scraped_hide')
		.itemInputs('tfc:large_soaked_hide')
		.itemOutputs('tfc:large_scraped_hide')
		.duration(100)
		.EUt(16)`
