### ISSUE TITLE
Realgar ores not spawning in the world

### ISSUE THREAD

**Issue by lagylarius** [TerraFirmaGreg-Team/Modpack-Modern#484]
### Version modpack Used

0.7.12

### Environment

Singleplayer

### New Worlds

Yes

### Expected Behavior

Realgar should spawn in the world since it's the only way to obtain arsenic and thus the only way to proceed from LV into MV

### Actual Behavior

After searching for hours on a new world using the ore prospector on random locations, realgar can't be found absolutely anywhere. It's either ridiculously rare or it's not spawning at all.

### Steps to Reproduce

Create a new world and search for realgar.

### Additional Information

Realgar is part of the surface copper vein (configured feature surface_copper.json), which doesn't spawn at all probably due to the elevation constraints never being met, even though it doesn't seem to spawn even on mountains and places where terrain generates after y=70.

Realgar is also the only ore from the surface veins that doesn't appear in any other normal veins.

Consider either making a LV alternative to getting arsenic or adding realgar to the normal copper vein.

**Comment by agreeable-frog** [comment]
1. Realgar does exist, but is very rare
2. There is no way to make arsenic from LV machines, but if you followed the quest orders you should have 1 MV machine : the electric blast furnace. It can be used to craft arsenic, I'll let you find the recipe.

**Comment by lagylarius** [comment]
Thank you so much. I found the recipe you were talking about and saw you can indeed get arsenic from cobaltite using the EBF.

Maybe the description of the Gallium Arsenide quest should change and say that you can actually do this, it just tells you to mine and centrifuge realgar instead.

**Comment by Exzept1on** [comment]
Fixed in 1.0.0 (dev)
