### ISSUE TITLE
Oil Sand Not Generating (Easy Fix)

### ISSUE THREAD

**Issue by vikingharold** [TerraFirmaGreg-Team/Modpack-Modern#486]
### Version modpack Used

0.7.11

### Environment

Singleplayer

### New Worlds

Yes

### Expected Behavior

Oil Sand should Generate

### Actual Behavior

Oil Sand doesn't Generate

### Steps to Reproduce

Just load in. :)

### Additional Information

Simple fix in
kubejs\server_scripts\tfc\tags.js
change "event.add('tfc:in_biome/veins', 'tfg:vein/normal_oil_sands')"
to "event.add('tfc:in_biome/veins', 'tfg:vein/normal_oilsands')"

this fixes it, I flew around in creative mode to check. and oil sand started to generate after this change.

**Comment by Exzept1on** [comment]
Fixed in 1.0.0 (dev)
