### ISSUE TITLE
Ошибка миксина: MixinTransformerError, вызванный критическим сбоем инъекции (InjectionError) при попытке перенаправления одного из методов в моде GregTech CEU.

### ISSUE THREAD

**Issue by AlphaCentauri3D** [TerraFirmaGreg-Team/Modpack-Modern#490]
### Версия модпака.

0.7.12

### Среда запуска

одиночная игра

### С какой стороны краш

Сервер

### Новые миры

Не уверен

### Действия по воспроизведению

1) Скачал все моды кроме некоторых косметических с curseforge. В особенности не ставил мод на bloom и вместо inventory sorting поставил inventory profiles next.
2) Запустил, загрузка игры прошла успешно, а потом ошибка KubeJS

### Отчет о сбое

[crash-2024-09-21_03.36.40-fml.txt](https://github.com/user-attachments/files/17081433/crash-2024-09-21_03.36.40-fml.txt)
[latest.log](https://github.com/user-attachments/files/17081436/latest.log)

### Дополнительная информация

ChatGPT:
Судя по отчету, причиной краша является ошибка при загрузке мода KubeJS. Ошибка связана с конфликтом в системе миксинов, который вызывает критическую ошибку при трансформации классов.
Основные моменты:
- Подозреваемый мод: **KubeJS (версия 2001.6.5-build.14)**.
- Ошибка миксина: **MixinTransformerError**, вызванный критическим сбоем инъекции (InjectionError) при попытке перенаправления одного из методов в моде GregTech CEU.
- Конкретный мод, вызывающий сбой: **TerraFirmaGreg-Core**.

**Comment by Xikaro** [comment]
Установи полностью модпак используя архив из релиза на гите, или установи используя curseforge, не качая моды отдельно и проверь повторно, так как у тебя установлены многие моды версии новее, чем те которые есть в релизе TFG, в частности стоит GregTech 1.4.1, а релиз [0.7.12](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/releases/tag/0.7.12) с версией 1.2.3a, новые версии модов не адаптированы, или еще не выпущена версия модпака с адаптацией к новым версиям модов
