### ISSUE TITLE
Unable to craft ZPM circuits

### ISSUE THREAD

**Issue by iQSJoker** [TerraFirmaGreg-Team/Modpack-Modern#498]
### Version modpack Used

0.7.12

### Environment

Forge Server

### New Worlds

Yes

### Expected Behavior

To be able to craft ZPM circuits.

### Actual Behavior

As per title, they cannot be crafted as the assembler recipe requires 48 1x annealed copper wire which only stacks to 32 and there aren't enough extra slots to fit the extra 16 wire in. 

A suggested fix was to use the large assembling factory which I thought would work but upon closer inspection the metal required to make that, Stellite-100, is uncraftable too.

### Steps to Reproduce

Try to craft the green, ZPM circuit which requires an IV assembler. You'll find the wires do not stack high enough to craft this.

![image](https://github.com/user-attachments/assets/f32c7588-dc5f-4cbd-ad67-1883f5403997)

**Comment by iQSJoker** [comment]
One solution would be to lessen the amount of annealed wire requires to 32 instead or 24 2x wire which would be the same amount.

Another solution if you'd prefer to gate this behind the large assembling factory would be to add a mixer recipe for Stellite-100 as it does have a chemical formula already
![image](https://github.com/user-attachments/assets/f684a6dc-5fb0-44cf-8996-afb49007afde)

4 Iron dust, 3 chromium dust, 2 tungsten dust and 1 molybdenum dust > 10 Stellite-100 dust would do it

**Comment by iQSJoker** [comment]
Please close this, I've found it's possible via the Alloy Blast Smelter & Large Circuit Assembler

**Comment by G93d14** [comment]
you can close issues you opened bud. don't need the git owner to do that
