### ISSUE TITLE
0.7.13 server hanging on startup

### ISSUE THREAD

**Issue by MememakerOG** [TerraFirmaGreg-Team/Modpack-Modern#501]
### Version modpack Used

0.7.13

### Environment

Forge Server

### Side Crashed

Server

### New Worlds

Unsure

### Steps to Reproduce

I tried updating my server from 0.7.12 to 0.7.13 and it work iniatly. But once the server went to sleep and was attempted to load again, I keep getting hung up on start up at this same spot.

### Crash Report

[debug.log](https://github.com/user-attachments/files/17197648/debug.log)
There is no crash report because the server doesn't crash, it just hangs until I force shut it down.

**Comment by Xikaro** [comment]
you are running a backup via FTB backups, wait until it finishes, or delete it, in the next version it will be removed from the server pack
