### ISSUE TITLE
Cutting Trees in 0.7.13 Crashes my game as soon a I left click on any kind of tree.

### ISSUE THREAD

**Issue by therealpro101** [TerraFirmaGreg-Team/Modpack-Modern#502]
### Version modpack Used

0.7.13

### Environment

Started on Forge Server, then tried Singleplayer same problem.

### Side Crashed

Client

### New Worlds

Yes

### Steps to Reproduce

I started by installing latest 0.7.13
I updated my world on my server from 0.7.12 > 0.7.13
Then me and my friends tried to chop trees and as soon as I left-clicked on a tree of any type I get a fatal error ended at the bottom.

### Crash Report

https://mclo.gs/kAKomdF
https://mclo.gs/YdV5zI8

### Additional Information

This is likely caused by panda falling tree mod. What steps ive taken to try to narrow down the problem: I tried singleplayer and multiplayer pre-0.7.12 worlds on 0.7.13 and tried a fresh install of 0.7.13 in both singleplayer and multiplayer same error occur.

**Comment by Exzept1on** [comment]
Funny, fixed in dev, update today, or tomorrow
