### ISSUE TITLE
Добавить мод TFC Canes - трости для снятия замедления при ходьбе через снег/траву

### ISSUE THREAD

**Issue by Jeggor** [TerraFirmaGreg-Team/Modpack-Modern#504]
### Версия модпака.

0.7.12

### Связанная проблема

Механика TFC - при ходьбе через высокую траву или снег игрок замедляется (даже в прыжке).
Выглядит логично, но хотелось бы иметь способ снимать этот дебаф

### Ваше решение

Простой мод, добавляющий деревянную и железную (из кованного железа) трости для снятия дебафа на скорость при ходьбе через траву.
Полезно на раннем этапе игры при исследовании мира

### Дополнительная информация

Ссылка на страницу мода на CurseForge: https://www.curseforge.com/minecraft/mc-mods/tfc-canes
Уже какое-то время играю с этим модом. Рецепты подтянулись автоматом, сам функционал рабочий.

**Comment by Exzept1on** [comment]
Fixed in 1.0.0
