### ISSUE TITLE
Добавить мод Visual Workbench - предметы остаются и отображаются в верстаке

### ISSUE THREAD

**Issue by Jeggor** [TerraFirmaGreg-Team/Modpack-Modern#505]
### Версия модпака.

0.7.12

### Связанная проблема

В GregTech много микрокрафта. Часто бывает ситуация, когда не хватает одного-двух компонентов для крафта и приходится  выходить из окна крафта и заново выкладывать рецепт.
Было бы удобно, если бы предметы оставались в верстаке при выходе из окна крафта.

### Ваше решение

Мод сохраняет предметы в верстаке, немного упрощая жизнь.
Плюс отображает предметы и результат крафта, может быть полезно в мультиплеере.

### Дополнительная информация

Ссылка на мод на CurseForge: https://www.curseforge.com/minecraft/mc-mods/visual-workbench
Нужно руками добавить TFC-шные верстаки в конфиг config/visual_workbench.json:
``` "tfc:wood/planks/acacia_workbench",
    "tfc:wood/planks/ash_workbench",
    "tfc:wood/planks/aspen_workbench",
    "tfc:wood/planks/birch_workbench",
    "tfc:wood/planks/blackwood_workbench",
    "tfc:wood/planks/chestnut_workbench",
    "tfc:wood/planks/douglas_fir_workbench",
    "tfc:wood/planks/hickory_workbench",
    "tfc:wood/planks/kapok_workbench",
    "tfc:wood/planks/mangrove_workbench",
    "tfc:wood/planks/maple_workbench",
    "tfc:wood/planks/oak_workbench",
    "tfc:wood/planks/palm_workbench",
    "tfc:wood/planks/pine_workbench",
    "tfc:wood/planks/rosewood_workbench",
    "tfc:wood/planks/sequoia_workbench",
    "tfc:wood/planks/spruce_workbench",
    "tfc:wood/planks/sycamore_workbench",
    "tfc:wood/planks/white_cedar_workbench",
    "tfc:wood/planks/willow_workbench"
```

**Comment by Exzept1on** [comment]
Fixed in 1.0.0
