### ISSUE TITLE
Дюпы 

### ISSUE THREAD

**Issue by 8oyNextDoor** [TerraFirmaGreg-Team/Modpack-Modern#508]
### Версия модпака.

0.7.14

### Среда запуска

Любая

### Новые миры

Да

### Ожидаемое поведение

Одинаковая стоимость/возврат при переработке предметов

### Фактическое поведение

3 меди + 1 красная пыль = 4 слитка красного сплава
![image](https://github.com/user-attachments/assets/6d959120-c3cf-48fb-877e-8b6ab447fe47)
превращаются в 4 пыли, которые далее
![image](https://github.com/user-attachments/assets/f13170ef-ce6e-49f2-a521-3496f022f96c)
На выходе имеем 4 меди + 16 красной пыли

-----------

Любой металл, который можно обрабатывать с тфк, требует 1 слиток на мясницкий нож
![image](https://github.com/user-attachments/assets/db3ca340-e252-4fba-9de6-ad32d1beda80)
Грег же требует 2
![image](https://github.com/user-attachments/assets/9a731b87-1a53-472a-b291-f14c4b9851f1)
и возвращает тоже 2 (и в дуговой, и в дробилке, и в экстракторе)
![image](https://github.com/user-attachments/assets/1b0d46a1-5459-4964-acdf-ff19c4446b85)

-----------

ЛВ корпус требует цветную сталь при крафте
![image](https://github.com/user-attachments/assets/dab28e34-723b-4531-954c-f67965037d50)
но не в сборщике
![image](https://github.com/user-attachments/assets/6ffa6af6-f0c5-4f18-ae94-2b6573c6ac6a)
и возвращает цветную (и в дуговой, и в дробилке)
![image](https://github.com/user-attachments/assets/5eb6b72e-b6fe-42ff-a226-b4caf8138628)

### Действия по воспроизведению

Рецепты в джеи

**Comment by Exzept1on** [comment]
Обо всем знали, исправлено в 1.0.0

**Comment by Exzept1on** [comment]
Fixed
