### ISSUE TITLE
Repeated Nonsensical Info Messages when running a server 

### ISSUE THREAD

**Issue by rrenode** [TerraFirmaGreg-Team/Modpack-Modern#509]
### Version modpack Used

0.7.14

### Environment

Forge Server Hosted on Windows 11

### New Worlds

Yes

### Expected Behavior

Expected the message to not log every tick.

### Actual Behavior

The following message logs every tick:

```[ne.dr.tf.ut.ca.Calendar/]: Calendar = false, Daylight = false (false) due to no players logged in (updated the value for when players log back in)```

![image](https://github.com/user-attachments/assets/bba75f99-8aed-4930-968e-6538d2c92d0e)

### Steps to Reproduce

1) Download server from GitHub for Modpack-Modern of version 0.7.14
2) Extract the zip contents to a directory
3) Run the `start_server.bat` file
4) After server initialization, see annoying messages that crowds the logs
5) Cry on modpack's Github

### Additional Information

No changes have been made to the modpack server files.

This will eventually be moved to a self-hosted linux server, though have only currently tested on Windows 11 GUI.

Assumed to be related to TFC and not the modpack. Only posted here in case I missed a config value or something simple.

I'm not actually playing the modpack. I was asked by a friend to set-up and manage a server for them.
In testing the server zip, I found this annoying message that keeps sending.

**Comment by Exzept1on** [comment]
Not a TFG issue, report to TFC git.
