### ISSUE TITLE
Can't complete stone tools quests

### ISSUE THREAD

**Issue by FakePizza** [TerraFirmaGreg-Team/Modpack-Modern#510]
### Version modpack Used

0.7.14

### Environment

Singleplayer

### New Worlds

Yes

### Expected Behavior

Completing the quest

### Actual Behavior

Quest does not compete

### Steps to Reproduce

Craft any stone tool with the stone tools quests available 

### Additional Information

the quest wants me to craft a greg tech stone tools while i only have access to the TFC tools

**Comment by G93d14** [comment]
when you craft a stone tool it should change to the gregtech version, that's how it was for me.

**Comment by FakePizza** [comment]
also tfc knife cant gather straw from plants

**Comment by gaschenk** [comment]
I can confirm that this happens on curseforge 0.8.0 as well. and there seems to be some kind of issue with the tags being removed/added in registerTFCItemTags

**Comment by TomslCon** [comment]
I am not using t launcher and have this issue. Trying to craft the tool gives the TFC tool and not the GT one

**Comment by G93d14** [comment]
your kubejs is broken, relog, and if that doesn't fix it, delete and
reinstall the instance.
