### ISSUE TITLE
alternator not making power

### ISSUE THREAD

**Issue by emil20022002** [TerraFirmaGreg-Team/Modpack-Modern#512]
### Version modpack Used

0.7.14

### Environment

Singleplayer

### New Worlds

Yes

### Expected Behavior

Alternator when given rotation from a shaft, and when configured input bus, it shod make power.

### Actual Behavior

Alternator when given rotation from a shaft, and when configured input bus, it shod make power. but it just says idling and not making power

### Steps to Reproduce

make the multi block
give rotation whit enough stress units  and speed
configure input bus.

### Additional Information

it dos not work in creative world ether.

**Comment by Exzept1on** [comment]
Fixed in 1.0.0 (dev version)

**Comment by Exzept1on** [comment]
fixed
