### ISSUE TITLE
No recipe for Neon, Krypton and Xenon

### ISSUE THREAD

**Issue by SirArevacoso** [TerraFirmaGreg-Team/Modpack-Modern#532]
### Version modpack Used

0.7.14

### Related Problem

Gases like Neon, Krypton, and Xenon are currently only obtainable with Liquid Nether Air or Liquid Ender Air inside a Distillation Tower. Due to the dimensions being disabled, the gases can't be obtained, making items like Neutronium-doped Monocrystalline Silicon boule uncraftable. Other than the gases being required for a number of recipes, they are also used in Fusion Reactor recipes.

### Your Solution

I would propose adding the possibility of obtaining Nether and Ender air in the overworld by removing the dimension requirement. Gregtech is balanced about collecting the air of each respective dimension which other than the gases leaves a lot of useful byproducts, so adding a recipe only for Neon, Krypton, and Xenon would make progression harder.

**Comment by Exzept1on** [comment]
True. Will be fixed in next upd.
