### ISSUE TITLE
advanced macerator output issues

### ISSUE THREAD

**Issue by Omaika69** [TerraFirmaGreg-Team/Modpack-Modern#535]
### Version modpack Used

0.7.14

### Environment

singleplater

### New Worlds

Unsure

### Expected Behavior

i expected the advanced macerator to give multiple outputs when destroying high pressure steam hammer

### Actual Behavior

when the steam hammer was put in the macerator i only got out  31 iron dust when i am expecting iron dust, bronze dust, wrought iron dust, and tin alloy dust
i also tried plant balls and only got 1 bio chaff instead of the expected 2-4

### Steps to Reproduce

put an item with multiple expected outputs into an advanced macerator and wait for the cycle to finish

**Comment by Pyritie** [comment]
advanced macerator is the mv one, right? macerators don't give multiple outputs until hv

**Comment by WaterMelwin** [comment]
> ### Version modpack Used
> 0.7.14
> 
> ### Environment
> singleplater
> 
> ### New Worlds
> Unsure
> 
> ### Expected Behavior
> i expected the advanced macerator to give multiple outputs when destroying high pressure steam hammer
> 
> ### Actual Behavior
> when the steam hammer was put in the macerator i only got out 31 iron dust when i am expecting iron dust, bronze dust, wrought iron dust, and tin alloy dust i also tried plant balls and only got 1 bio chaff instead of the expected 2-4
> 
> ### Steps to Reproduce
> put an item with multiple expected outputs into an advanced macerator and wait for the cycle to finish
> 
> ### Additional Information
> _No response_

have you tried reading

**Comment by Omaika69** [comment]
> advanced macerator is the mv one, right? macerators don't give multiple outputs until hv

apparently ive played GTCE in the past and didn't realize the second slot want open until HV, i also though you got all slots on the lower machines when "recycling" i guess arc furnace it is
