### ISSUE TITLE
FTB quests is broken

### ISSUE THREAD

**Issue by rat123fuckthissititwasa** [TerraFirmaGreg-Team/Modpack-Modern#540]
### Version modpack Used

0.7.14

### Environment

both

### New Worlds

Yes

### Expected Behavior

expected: show the normal items that are requierd

### Actual Behavior

its not showing it (shows smart filter from ffs (ftb filter system) as the item)

### Steps to Reproduce

we dont know but we both have it 
it just started yesterday (maybe becuse of the modpack update)

### Additional Information

the quests still work its just anoying to look at and not see the item

fixed temp but might come back later on( it got fixed magicly while trying to report it lol)

**Comment by lazylion93** [comment]
sounds like something in your installation got bonked up. there's no such thing as a smart filter from FFS.
all quests that have filters as the item to complete uses gregtech ones or maybe the create ones.

**Comment by Exzept1on** [comment]
Bad installation issue.
