### ISSUE TITLE
Merge PR for updated TFC Shaders for Complimentary

### ISSUE THREAD

**Issue by Rovetown** [TerraFirmaGreg-Team/Modpack-Modern#546]
### Version modpack Used

0.7.14

### Your Solution

There has been someone who updated the TFC/TFG Shader Compat for Complimentary so that it works for the newest Complimentary versions (so Complimentary r5.x).

This is your [ TFG Modern Shaders Repo](https://github.com/TerraFirmaGreg-Team/Shaders-Modern) with the old block.properties file that is currently outdated

this is the [pull request](https://github.com/TerraFirmaGreg-Team/Shaders-Modern/pull/2) the user made that updated the block.properties file so it works with the newer Complimentary versions (Complimentary r5.x)

Could you maybe merge the PR and update the [CurseForge Page](https://www.curseforge.com/minecraft/modpacks/terrafirmagreg/files/5772962)

**Comment by G93d14** [comment]
this person living in the future already on 0.7.15 while the rest of us commoners are on 0.7.14

**Comment by Exzept1on** [comment]
within 1-2 days will be merged and sended update to curse

**Comment by Exzept1on** [comment]
Shaders zip waiting for approving on curse, closed.
