### ISSUE TITLE
В квестах и крафтах отображается сера и графит только из GregTech

### ISSUE THREAD

**Issue by Joy1o** [TerraFirmaGreg-Team/Modpack-Modern#547]
### Версия модпака.

0.7.14

### Среда запуска

одиночная игра

### Новые миры

Да

### Ожидаемое поведение

В квестах будут засчитывать любую руду серы и графита за выполнение квеста. В крафтах будет так же использоваться любая руда серы и графита

### Фактическое поведение

В квестах и крафтах отображается сера и графит только из GregTech, а добыть можно только серу и графит из TFC. Переделать данные руды на данном этапе развития в игре не возможно, продвижение дальше так же не возможно, из-за того что я не могу сделать огнеупорную глину.

### Действия по воспроизведению

1 добыл руду из TFC 
2 не получил ачивку
3 не смог скрафтить графитовую пудру

### Дополнительная информация

Стоит заново пересмотреть работу с рудами и квесты с рудами

**Comment by Exzept1on** [comment]
Каким образом ты добыл TFC вариант серной руды?

**Comment by Joy1o** [comment]
Извиняюсь, я понял свою ошибку. В первый раз нужно добывать графит молотом, чтобы выпал правильный графит. Для этого мне пришлось пересмотреть десяток прохождений и только потом я заметил в квестах совет добывать графит молотом. Думаю можно добавить книжку для помощи в прохождении для таких одарённых как я.

**Comment by Exzept1on** [comment]
Уже добавил пояснения в ветке, 1.0.0, закрываю
