### ISSUE TITLE
Reinforced glass is not obtainable via glassworking

### ISSUE THREAD

**Issue by josiah-roberts** [TerraFirmaGreg-Team/Modpack-Modern#552]
### Version modpack Used

0.7.14

### Environment

Official Server

### New Worlds

Yes

### Expected Behavior

It's possible to glassblow reinforced glass

### Actual Behavior

It's not possible to glassblow reinforced glass, because the flatten step cannot be performed. TFC Hot or Not prevents holding a paddle in the offhand, so the flatten step cannot be performed.

### Steps to Reproduce

1. Heat glass
2. Put a paddle in your offhand
3. Try to flatten it
4. Observe as TFC Hot or Not makes you drop the blowpipe

**Comment by josiah-roberts** [comment]
Server lag issue; holding flatten ~2x as long as it takes the animation to play causes it to work.

**Comment by kafuuchino-desu** [comment]
this is absolutely very confusing since the glasswork chapter in the guidebook clearly states that you hold the blowpipe in your main hand instead of offhand
![image](https://github.com/user-attachments/assets/ec22bcd7-36fa-4ec9-9caa-32e62961310a)
