### ISSUE TITLE
[EN] Macerating ULV Machines dont give all products+

### ISSUE THREAD

**Issue by KoboDev** [TerraFirmaGreg-Team/Modpack-Modern#560]
### Version modpack Used

0.7.14

### Environment

Singleplayer, Open to LAN

### New Worlds

Yes

### Expected Behavior

Macerating old ULV machines should give as the JEI recipe describes.
12 Bronze Dust
5 Wrought Iron Dust
2 Diamond Dust
2 Tin Alloy Dust
![image](https://github.com/user-attachments/assets/74426b5f-6085-431d-baae-06295e38163e)

### Actual Behavior

Macerating old ULV Machines such as the ULV High Pressure Steam Macerator yields only:
12 Bronze Dust.

### Steps to Reproduce

1. Put your ULV machine, macerator or other into an LV or higher Macerator.
2. Watch as your products get wasted.
3. So much bronze.

### Additional Information

I have done this in the ULV macerator by accident and watched it become 12 bronze, building up to the LV macerator should give all the products back. (As LV machines start producing expecting there to be 2 more slots, I.e Centrifuge and Ore washer, so it can output chance products, however it is not doing that, expectedly because it maybe an 0% chance or an bug).

**Comment by lazylion93** [comment]
Not a TFG issue. Only HV Macerators and above give outputs in additional slots.

**Comment by WaterMelwin** [comment]
> ### Version modpack Used
> 0.7.14
> 
> ### Environment
> Singleplayer, Open to LAN
> 
> ### New Worlds
> Yes
> 
> ### Expected Behavior
> Macerating old ULV machines should give as the JEI recipe describes. 12 Bronze Dust 5 Wrought Iron Dust 2 Diamond Dust 2 Tin Alloy Dust ![image](https://private-user-images.githubusercontent.com/78581464/380355355-74426b5f-6085-431d-baae-06295e38163e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5MzExMzQsIm5iZiI6MTcyOTkzMDgzNCwicGF0aCI6Ii83ODU4MTQ2NC8zODAzNTUzNTUtNzQ0MjZiNWYtNjA4NS00MzFkLWJhYWUtMDYyOTVlMzgxNjNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDA4MjAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwY2ZkOWNmZWVlNDQ5OGEzMGRmNTkxMzcyZWQyZDQ4MDQzNGZiMDZkNjI3N2U1Y2MyMjAxMWIxNjE2MTU4MmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FTTPEB4iiLU2P0cGomnnQPccNcX_n4uCbif0ra4oQ60)
> 
> ### Actual Behavior
> Macerating old ULV Machines such as the ULV High Pressure Steam Macerator yields only: 12 Bronze Dust.
> 
> ### Steps to Reproduce
> 1. Put your ULV machine, macerator or other into an LV or higher Macerator.
> 2. Watch as your products get wasted.
> 3. So much bronze.
> 
> ### Additional Information
> I have done this in the ULV macerator by accident and watched it become 12 bronze, building up to the LV macerator should give all the products back. (As LV machines start producing expecting there to be 2 more slots, I.e Centrifuge and Ore washer, so it can output chance products, however it is not doing that, expectedly because it maybe an 0% chance or an bug).

wow thats how greg works!

**Comment by Exzept1on** [comment]
Skill issue
