### ISSUE TITLE
[EN] Maceratoring High Pressure ULV Machines: Forge Hammer, Compressor, Furnace, Rock Crusher, Macerator & Extractor; Yeilds materials not found in its crafting recipe.

### ISSUE THREAD

**Issue by KoboDev** [TerraFirmaGreg-Team/Modpack-Modern#561]
### Version modpack Used

0.7.14

### Environment

Singleplayer

### New Worlds

Yes

### Expected Behavior

Crafting ULV Machines such as the High Pressure Macerator requires 8 Wrought Iron Plates, 2 Small Tin Alloy Fluid Pipes, 3 Bricks, an spare hammer, and 3 steel plates.

Going into the LV stage of your journey you would like to scavenge your machines for rare minerals.

Macerating ULV Machines like Steam Liquid Boilers, Solar Boilers, or maybe desperately your Solid Boiler gives your resources (more or less) back.

### Actual Behavior

However for the rest of machines (discluding low pressure).
It shows these as the resources getting back.
![image](https://github.com/user-attachments/assets/4c7baa4f-b706-4288-9da2-27bbeee57f50)
![image](https://github.com/user-attachments/assets/eaa98cbd-7efa-4100-b4b0-7aa699ba1763)
![image](https://github.com/user-attachments/assets/15ce42c1-31f5-464e-b508-1d94553dae77)

And the personal favorite, the forge hammer.
Which gives 31, Iron dust back.
In a Recipe that only requires 8 at most, being transformed into Wrought Iron.
![image](https://github.com/user-attachments/assets/50a353a8-8f00-4bcf-85b1-8e02d61aeba7)

### Steps to Reproduce

1. Macerate any ULV machine described here.
2. Watch as the recipe turns into a mess.
3. Profit???

### Additional Information

This is an connected issue to #560 as macerating these machines also dont give full product for being in an LV machine (The Minimum Ive saw that gives multiple products/byproducts.)

**Comment by 8oyNextDoor** [comment]
Lv and mv macerator sonly give the items from the first slot, extra items are only produced starting from hv, use an arc furnace instead

**Comment by Exzept1on** [comment]
skill issue
