### ISSUE TITLE
Ingot mold casting using wrong value for recipes

### ISSUE THREAD

**Issue by LucemDivinus** [TerraFirmaGreg-Team/Modpack-Modern#566]
### Version modpack Used

0.8.0

### Environment

Single player

### New Worlds

Unsure

### Expected Behavior

cast molten liquid into mold
ingot should come out

### Actual Behavior

molten liquid fills the ingot mold, but only to 100mb instead of the required 144
![ingot mold bug](https://github.com/user-attachments/assets/f2f4509c-6da0-4dae-93bb-b818e943e102)

### Steps to Reproduce

on a 0.8.0 world cast any molten liquid into the ingot mold
mold gets filled only to 100mb when ingots require 144mb

### Additional Information

i downgraded my pack to the previous version, ingot mold holds the required 144mb. something in the new update changed the values.

**Comment by Exzept1on** [comment]
Oh no, it happened because Xikaro badly publish release on curse (no cfgs for tfc and etc mods)
![image](https://github.com/user-attachments/assets/3f71be9a-9bbd-4392-838d-ceb789eff520)
I think will be fixed today, thanks for report

**Comment by iCloudly** [comment]
Happening to me in the latest version
