### ISSUE TITLE
Гевея сажанец

### ISSUE THREAD

**Issue by SteelTecher** [TerraFirmaGreg-Team/Modpack-Modern#573]
### Версия модпака.

0.8.1

### Среда запуска

Одиночная игра

### Новые миры

Да

### Ожидаемое поведение

будет Сажанец

### Фактическое поведение

Нету никаких сажанцей кроме фруктов но для гивеи нужно

### Действия по воспроизведению

Гевею сломать

**Comment by Exzept1on** [comment]
Что?

**Comment by SteelTecher** [comment]
саженец резинового дерева нельзя получить а для теплиц и зеленого дома нужен

**Comment by SteelTecher** [comment]
Нашел проблему при миграции что то произошло и все на чистой все норм
