### ISSUE TITLE
Не работают рецепты в прокатном станке

### ISSUE THREAD

**Issue by HugeTeck** [TerraFirmaGreg-Team/Modpack-Modern#576]
### Версия модпака.

0.8.1

### Среда запуска

Одиночная игра и сервер Forge

### Новые миры

Да

### Ожидаемое поведение

Из слитка должно производится 2 стержня данного металла.

### Фактическое поведение

Из стержня делается стержень того же материала
![image](https://github.com/user-attachments/assets/14bcaf1a-2c30-4872-b2a5-d0d014971039)

### Действия по воспроизведению

.

**Comment by Exzept1on** [comment]
Должен производиться 1 стержень, а не 2, эни вей тут баг, исправлено в https://github.com/TerraFirmaGreg-Team/Modpack-Modern/commit/3a62265b5346f688d62b746435593ff6563741e1
