### ISSUE TITLE
Add TFC Curios Weight

### ISSUE THREAD

**Issue by Amerith** [TerraFirmaGreg-Team/Modpack-Modern#599]
### Version modpack Used

0.7.14

### Related Problem

Currently the weight for items such as barrels, large vessels, and other such items aren't properly taken into account when worn on the back. This causes strange interactions such as being able to carry two of said items when full.

### Your Solution

A new mod has come out recently which is supposed to fix this issue and make weight properly calculated for curio slots. https://www.curseforge.com/minecraft/mc-mods/tfc-curios-weight

**Comment by WaterMelwin** [comment]
is that not the whole point of carrying it on the back lol

**Comment by Amerith** [comment]
> is that not the whole point of carrying it on the back lol

There's arguments I have for both sides honestly. On one end I like the exhaustion canceling effect wearing them on the back has when weight isn't calculated. The part I don't like about it not being calculated is being able to carry two large vessels full of food or two barrels full of liquid.

**Comment by Pyritie** [comment]
you can also just carry a ton of full vessels/barrels/etc in a backpack without any sort of downsides so "fixing this" would just make everyone do that workaround instead

**Comment by Amerith** [comment]
> you can also just carry a ton of full vessels/barrels/etc in a backpack without any sort of downsides so "fixing this" would just make everyone do that workaround instead

Dang. If it's so easy to workaround I suppose it is kind of worthless to add then. Haven't messed around with the modded storage much so I didn't realize this. Closing this then since there's no point in keeping it up.
