### ISSUE TITLE
[🐛]: Stiscy resin is uncraftable 

### ISSUE THREAD

**Issue by D3m0no** [TerraFirmaGreg-Team/Modpack-Modern#612]
### Was this bug reported before?

- [X] No, it was not.

### Version modpack used

0.7.14

### Environment

singleplayer

### New Worlds

Yes

### Please provide a link to your latest.log, if relevant

https://mclo.gs/gItptWT

### Expected Behavior

I tried to craft sticky resin on my "quick learn how to do thing with creative help" world. For experiment i used pod and vat as well.

### Actual Behavior

I waited and used maybe 8 logs in firepit and I got sticky resin once, I don't even know how. I tried with differend tipes of sulfur items, normal (tfc:powder/sulfur) and dust (gtceu:sulfuer_dust).

### Steps to Reproduce

1) colect materia.tfg.latex (game don't show name corect) in wooden bucket
2) pour to the pod/vat (fire under pod)
3) add sulfur

### Additional Information

I couldn't get crushed sulfur (if its possible with black bronze tools) form the ore.

**Comment by WaterMelwin** [comment]
huh

**Comment by Pyritie** [comment]
put the gregtech sulphur in a quern to get the tfc sulfur

don't forget to close the lid on your vat either

**Comment by D3m0no** [comment]
Okey, I've got it, its taking so long in the pod. And I didn't know how to use vat correctly.
