### ISSUE TITLE
[🐛]: Textures missing for decorated armor

### ISSUE THREAD

**Issue by SverhRazum-Nah** [TerraFirmaGreg-Team/Modpack-Modern#613]
### Was this bug reported before?

- [X] No, it was not.

### Version modpack used

0.8.1

### Environment

одиночная игра

### New Worlds

Yes

### Please provide a link to your latest.log, if relevant.

.

### Expected Behavior

Наличие текстур

### Actual Behavior

Отсутствие текстур
![image](https://github.com/user-attachments/assets/b6040edd-7755-40dd-b60c-74ceebcca20c)

### Steps to Reproduce

украсить броню чем угодно

### Additional Information

Возможно это баг самой теарфирмы или типа того

**Comment by SverhRazum-Nah** [comment]
![image](https://github.com/user-attachments/assets/36e4498e-7497-4acd-9631-eef206b525a1)
ну кстати не у всей

**Comment by Pyritie** [comment]
This looks like a problem with your texture pack, it works fine for me 
![image](https://github.com/user-attachments/assets/6b587762-2c47-41a0-bf15-6244b324d3f7)

**Comment by SverhRazum-Nah** [comment]
> This looks like a problem with your texture pack, it works fine for me ![image](https://private-user-images.githubusercontent.com/1402116/392570271-6b587762-2c47-41a0-bf15-6244b324d3f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNTA5MDMsIm5iZiI6MTczMzM1MDYwMywicGF0aCI6Ii8xNDAyMTE2LzM5MjU3MDI3MS02YjU4Nzc2Mi0yYzQ3LTQxYTAtYmYxNS02MjQ0YjMyNGQzZjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDRUMjIxNjQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDQyNzIzNzk3MTMzMWMwNWFjNGEzNTkzMDYzNGUxZjUxMjQxODZkNWVmNDAxZjdhYzJlYzJlMGRjNTQ4YmNhMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.r8a2uCESY-HCCJu_WdlUKvNPESiZQm43WQgJ6rGfeNo)

Закинул иалору на рассмотрение. Возможно изза его текстурпака проблема

**Comment by WaterMelwin** [comment]
stop using 0.8.1

**Comment by SverhRazum-Nah** [comment]
> stop using 0.8.1

Используя 0.8.1 я приближаю обновление,  тестируя версию и помогая исправить ошибки,  так что не понимаю почему ты хочешь чтоб я перестал на ней играть...

**Comment by Xikaro** [comment]
https://github.com/ilaores/ILAORE-s-TFC-32x32
Вопрос уже был адресован разработчику ресурспака
тут закрываю
