### ISSUE TITLE
[🐛]: Sprinkler are still not usable with other pipes in 0.8.1.

### ISSUE THREAD

**Issue by Karn4132** [TerraFirmaGreg-Team/Modpack-Modern#618]
### Was this bug reported before?

- [X] No, it was not.

### Version modpack used

0.8.1

### Environment

Singleplayer

### New Worlds

Yes

### Please provide a link to your latest.log, if relevant.

-

### Expected Behavior

Sprinklers should be usable with pipes from other mods like GT or Create.

### Actual Behavior

![image](https://github.com/user-attachments/assets/365545e6-5384-4671-bff3-4cbd8847982d)
![image](https://github.com/user-attachments/assets/519f0fba-724c-45b5-8b6e-b0d8af90aa11)
![image](https://github.com/user-attachments/assets/a108c277-56e5-4f3b-b347-fc319fea6e3e)

### Steps to Reproduce

Attached a sprinkler under a GT bronze fluid pipe. It didn't work
Placed a water drum above a sprinkler and enebled an auto output. Also didn't work.

### Additional Information

I'm not sure if it was not really fixed in 0.8.1 or I just couldn't connect a sprinkler to a water output. Please let me know if I miss something.

**Comment by SverhRazum-Nah** [comment]
У меня в мире работает. Есть ли вода в трубе? Надо обновлять теплицу каждый раз. Возможно в радиусе 2 блоков нет грядок (такой радиус его работы)

**Comment by Karn4132** [comment]
The pipes were transporting directly to a sprinkler and a tank nearby according to my screenshots and both sprinklers acknowledge the greenhouse.  
Yes, I tested a sprinkler without any beds below. Do I have to place gardening beds under a sprinkler for it to work correctly?

**Comment by SverhRazum-Nah** [comment]
> The pipes were transporting directly to a sprinkler and a tank nearby according to my screenshots and both sprinklers acknowledge the greenhouse. Yes, I tested a sprinkler without any beds below. Do I have to place gardening beds under a sprinkler for it to work correctly?

Да. У меня работает, тк рядом есть горшки для растений. Так же бочка в трубы передаёт только вниз (так же как ты пытался передать воду в спринклер)

**Comment by Karn4132** [comment]
![image](https://github.com/user-attachments/assets/e92d89b9-55d3-4282-9f5f-4b40e93a95dd)
Welp, a few large beds and a bunch of trellis planters doesn't help at all.
I'm pretty sure that this sprinkler is already under a suitable condition. A greenhouse, a water source and gardens bed just like what you said.

**Comment by SverhRazum-Nah** [comment]
> Author

ну, они в 3 блоках от разбрызгивателя...
Ладно, сейчас зайду в свой мир

**Comment by SverhRazum-Nah** [comment]
![image](https://github.com/user-attachments/assets/5f6fb739-0383-4fb7-bfab-cb3c2508f8ac)
Как я и сказал, у меня всё работает
![image](https://github.com/user-attachments/assets/1108d910-13d2-4d38-8855-b3553eb2599e)
проверь есть ли в трубах вода

**Comment by SverhRazum-Nah** [comment]
И можешь для уверенности показать то как ты устанавливаешь бочку для передачи жидкости в трубы?

**Comment by SverhRazum-Nah** [comment]
![image](https://github.com/user-attachments/assets/6c2b01c7-cf9f-4d89-ab8f-661259fcade4)
напрямую с бочки не работает. Нужны трубы

**Comment by SverhRazum-Nah** [comment]
![image](https://github.com/user-attachments/assets/4f58e3bf-b09d-4e5e-b747-40990d22dde6)

**Comment by Karn4132** [comment]
![image](https://github.com/user-attachments/assets/296fd087-bd23-438b-b53e-0a7bd880d205)
![image](https://github.com/user-attachments/assets/ed589aa8-e662-46d5-abbe-141b5d21a19b)
Pipe is full of water, but my sprinkler still doesn't work.

**Comment by SverhRazum-Nah** [comment]
Проблему решил. Можнно закрывать.
![image](https://github.com/user-attachments/assets/677f7b19-46ca-4cdc-bf62-dc33dcd65b24)
