### ISSUE TITLE
[🐛]: Attempting to make a GregTech empty wooden form in crafting grid results in lumber, not a wooden form.

### ISSUE THREAD

**Issue by MooseMan870** [TerraFirmaGreg-Team/Modpack-Modern#623]
### Was this bug reported before?

- [X] No, it was not.

### Version modpack used

0.6.15

### Environment

Singleplayer

### New Worlds

Yes

### Please provide a link to your latest.log, if relevant.

N/A

### Expected Behavior

I expected to be able to make an empty wooden form from GregTech.

![image](https://github.com/user-attachments/assets/76c3b62f-23c3-4070-9892-d8e059f2c282)

### Actual Behavior

The recipe for lumber appears to have priority over the recipe for the empty wooden form, and as a result an empty wooden form is uncraftable.

![image](https://github.com/user-attachments/assets/54e9c0b9-26a1-451f-9ff6-b65b731a2ae8)

### Steps to Reproduce

Attempt to crat an empty wooden form.

**Comment by G93d14** [comment]
1. why are you so far back as to be playing 0.6.15 instead of 0.7.14?
2. wooden forms are made by compressing wood dust.

**Comment by MooseMan870** [comment]
Its an old install, is it safe to update with my world?
