### ISSUE TITLE
[🐛]: Pottery wont place on dirt.

### ISSUE THREAD

**Issue by 901238746** [TerraFirmaGreg-Team/Modpack-Modern#627]
### Was this bug reported before?

- [x] No, it was not.

### Version modpack used

0.7.14

### Environment

Singleplayer

### New Worlds

Yes

### Please provide a link to your latest.log, if relevant.

https://mclo.gs/25CsR3C

### Expected Behavior

Shift rightclicking places items on the floor.

### Actual Behavior

Nothing happens.

### Steps to Reproduce

1) Dig a hole in some dirt.
2) Shift right click the dirt with pottery in hand.
3) See bug.

### Additional Information

This makes pit kilns impossible.
Also Im using curseforges app to run it.
Im using forge modloader.
Reinstall still has issues.

### Specs
OS: Windows 11
CPU: AMD Ryzen 5 4500U w/ integrated graphics
RAM: 16 GB
GPU: integrated Radeon graphics

**Comment by 901238746** [comment]
I love the 3 missing mods.toml files. the logs say that they are missing.

**Comment by G93d14** [comment]
this looks like a bad install of the modpack, verify your file integrity or recreate the instance

**Comment by 901238746** [comment]
ok

**Comment by 901238746** [comment]
reinstalling it rn

**Comment by 901238746** [comment]
Is my computer just cursed or what. its still broken on a reinstall. gonna try to somehow manual install it without curseforges "help".

**Comment by 901238746** [comment]
ok manual install is impossible. I dont even get the mods in the modpack.zip. all I get is a modlist and some configs.

**Comment by 901238746** [comment]
https://drive.google.com/file/d/1XeGxXSSP0I0BQTztvbrh_m925HF1xMUH/view?usp=sharing
Forge profile ^

**Comment by 901238746** [comment]
Also just in case my PC specs:
OS: Windows 11
CPU: AMD Ryzen 5 4500U w/ integrated graphics
RAM: 16 GB
GPU: integrated Radeon graphics

**Comment by 901238746** [comment]
Just let me get wood man :,(

**Comment by Pyritie** [comment]
you could try a different modloader maybe? the curseforge one worked fine for me

**Comment by Pyritie** [comment]
also, you fire pottery in a pit kiln by pressing V, not by sneak+right-clicking

**Comment by 901238746** [comment]
oh ok. I will try that

**Comment by 901238746** [comment]
All the terrafirmacraft tutorials said to shift right click so that confused me

**Comment by 901238746** [comment]
no bug, just a misunderstanding.
