### ISSUE TITLE
Нет текстуры у слитка (Свинец) 

### ISSUE THREAD

**Issue by Latom-alex** [TerraFirmaGreg-Team/Modpack-Modern#89]
### Вы используете последнюю доступную версию?

Yes

### Среда запуска

Сервер

### Новые миры

Да

### Ожидаемое поведение

![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/150847107/f5c1197a-c37b-4134-94ee-6904d2c911ae)
Возможно проблема мода. но просто на всякий напишу ( у свинца текстурка как у глины Черная)
Так-же по какой-то причине в кладке слитков. Свинец отображается как Неизвестный металл xD
![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/150847107/134db14b-91c0-4543-8c86-e60ca255999e)

### Фактическое поведение

.

### Действия по воспроизведению

.

**Comment by SpeeeDCraft** [comment]
Там у всех слитков, что не принадлежат тфк, нужно текстуру для каждого сделать, лоу приорити крч

**Comment by SpeeeDCraft** [comment]
Исправлено в 0.8.0
