### ISSUE TITLE
Сортировка не работает в GT хранилищах

### ISSUE THREAD

**Issue by Yorodoshi** [TerraFirmaGreg-Team/Modpack-Modern#93]
### Вы используете последнюю доступную версию?

Yes

### Среда запуска

Сервер|Одиночная 

### Новые миры

Да

### Ожидаемое поведение

Сортировка спасёт меня от срача

### Фактическое поведение

Сортировка не работает

### Действия по воспроизведению

Жал колёсико мыши

**Comment by Yorodoshi** [comment]
В версии 0.1.1 баг ушёл

**Comment by Exzept1on** [comment]
Исправлено в 1.0.0, использованием мода InventoryTweaksRefoxed
